// English for Arabic exercises data text. Keys are the exact Arabic strings from the data files.
export const EN_EXERCISES: Record<string, string> = {
  'هاشيموتو (قصور الغدة المناعي)': 'Hashimoto\'s thyroiditis (autoimmune hypothyroidism)',
  'جريفز (فرط نشاط الغدة)': 'Graves\' disease (overactive thyroid)',
  'روماتويد مفصلي': 'Rheumatoid arthritis',
  'صدفية أو التهاب مفاصل صدفي': 'Psoriasis or psoriatic arthritis',
  'الذئبة الحمراء (لوبس)': 'Systemic lupus erythematosus (lupus)',
  'سكر النوع الأول': 'Type 1 diabetes',
  'سكر النوع التاني': 'Type 2 diabetes',
  'مقاومة الإنسولين': 'Insulin resistance',
  'تكيس المبايض': 'Polycystic ovary syndrome (PCOS)',
  'حساسية القمح (سيلياك)': 'Celiac disease (gluten intolerance)',
  'التصلب المتعدد (MS)': 'Multiple sclerosis (MS)',
  'كرون أو القولون التقرحي': 'Crohn\'s disease or ulcerative colitis',
  'كورتيزون (بريدنيزولون وغيره)': 'Corticosteroids (prednisolone, etc.)',
  'هرمون الغدة (ليفوثيروكسين / يوثيروكس)': 'Thyroid hormone (levothyroxine / Euthyrox)',
  'إنسولين': 'Insulin',
  'ميثوتركسات': 'Methotrexate',
  'علاج بيولوجي أو مثبط مناعة': 'Biologic or immunosuppressant',
  'هيدروكسي كلوروكين (بلاكونيل)': 'Hydroxychloroquine (Plaquenil)',
  'حاصرات بيتا (كونكور، إندرال)': 'Beta blockers (Concor, Inderal)',
  'مسيّل للدم': 'Blood thinner',
  'الركبة': 'Knee',
  'الضهر': 'Back',
  'الكتف': 'Shoulder',
  'الرسغ / الإيد': 'Wrist / hand',
  'السبت': 'Saturday',
  'الأحد': 'Sunday',
  'الاتنين': 'Monday',
  'التلات': 'Tuesday',
  'الأربع': 'Wednesday',
  'الخميس': 'Thursday',
  'الجمعة': 'Friday',
  'سبت': 'Sat',
  'أحد': 'Sun',
  'اتنين': 'Mon',
  'تلات': 'Tue',
  'أربع': 'Wed',
  'خميس': 'Thu',
  'جمعة': 'Fri',
  'سكوات بالبار': 'Barbell back squat',
  'ضغط الرجل (ليج برس)': 'Leg press',
  'هيب ثرست على الماكينة': 'Machine hip thrust',
  'رومانيان ديدليفت بالدمبل': 'Dumbbell Romanian deadlift',
  'ليج كيرل (خلفي)': 'Lying leg curl',
  'ليج إكستنشن (أمامي)': 'Leg extension',
  'أبدكشن على الماكينة': 'Hip abduction machine',
  'لانجز بالدمبل': 'Dumbbell lunges',
  'سمانة على الماكينة': 'Machine calf raise',
  'تشست برس بالدمبل': 'Dumbbell chest press',
  'تشست برس على الماكينة': 'Machine chest press',
  'بيك ديك (فراشة)': 'Pec deck (fly)',
  'لات بول داون': 'Lat pulldown',
  'سحب كيبل وانت قاعد': 'Seated cable row',
  'دمبل رو بإيد واحدة': 'One-arm dumbbell row',
  'شولدر برس بالدمبل': 'Dumbbell shoulder press',
  'رفرفة جانبي خفيف': 'Light lateral raise',
  'فيس بول بالكيبل': 'Cable face pull',
  'بايسبس كيرل': 'Biceps curl',
  'بايسبس على الكيبل بالحبل': 'Cable rope biceps curl',
  'ترايسبس بوش داون': 'Triceps pushdown',
  'إنكلاين برس بالدمبل': 'Incline dumbbell press',
  'إنكلاين برس على الماكينة': 'Incline machine press',
  'شولدر برس على الماكينة': 'Machine shoulder press',
  'رفرفة جانبي بالكيبل': 'Cable lateral raise',
  'ترايسبس فوق الراس بالكيبل': 'Cable overhead triceps extension',
  'عقلة بالماكينة المساعدة': 'Assisted pull-up machine',
  'سحب على الماكينة بسند للصدر': 'Chest-supported machine row',
  'سحب بدراع مفرود بالكيبل': 'Cable straight-arm pulldown',
  'كتف خلفي على البيك ديك': 'Rear delt fly on pec deck',
  'هامر كيرل بالدمبل': 'Dumbbell hammer curl',
  'هاك سكوات على الماكينة': 'Machine hack squat',
  'سبليت سكوات بالدمبل': 'Dumbbell split squat',
  'سمانة وانت قاعد': 'Seated calf raise',
  'جلوت كيك باك بالكيبل': 'Cable glute kickback',
  'بلانك': 'Plank',
  'ديد باج': 'Dead bug',
  'HIIT على المشاية (جري متقطع)': 'Treadmill HIIT (interval running)',
  'عجلة ثابتة': 'Stationary bike',
  'مشي على المشاية بميل': 'Incline treadmill walk',
  'سكوات بوزن الجسم': 'Bodyweight squat',
  'قعدة وقومة من على الكرسي': 'Chair sit-to-stand',
  'جلوت بريدج': 'Glute bridge',
  'لانجز ورا': 'Reverse lunges',
  'ضغط على الكنبة أو الحيطة': 'Incline push-up (couch or wall)',
  'دفع بالأستك قدامك': 'Resistance band chest press',
  'سحب بزجاجات مياه أو أستك': 'Row with water bottles or band',
  'سحب بالأستك وانت قاعد': 'Seated resistance band row',
  'ضغط كتف بزجاجات مياه': 'Water bottle shoulder press',
  'بيرد دوج': 'Bird dog',
  'سمانة على السلمة': 'Calf raise on a step',
  'جامبينج جاك': 'Jumping jacks',
  'ماونتن كلايمبر': 'Mountain climbers',
  'مشي سريع في المكان': 'Marching in place',
  'مشي سريع برا أو على المشاية': 'Brisk walk outdoors or on a treadmill',
  'سومو سكوات بزجاجة مياه': 'Sumo squat with a water bottle',
  'رفع الرجل لورا على الأربع': 'Quadruped leg kickback',
  'رفع الرجل جانبي وانت نايم': 'Side-lying leg raise',
  'بايسبس بالأستك أو زجاجات مياه': 'Band or water bottle biceps curl',
  'ترايسبس على الكرسي': 'Chair triceps dips',
  'بلانك جانبي على الركبة': 'Kneeling side plank',
  'جامبينج جاك من غير نط': 'Step jacks (no jumping)',
  'إطالات ومرونة للجسم كله': 'Full-body stretching and mobility',
  'تنفس واسترخاء': 'Breathing and relaxation',
  'الجزء العلوي': 'Upper body',
  'الجزء السفلي': 'Lower body',
  'Push: صدر وكتف وترايسبس': 'Push: chest, shoulders & triceps',
  'Pull: ضهر وباي': 'Pull: back & biceps',
  'Legs: رجل': 'Legs',
  'تمرين بيت: قوة': 'Home workout: strength',
  'تمرين بيت: كارديو وبطن': 'Home workout: cardio & core',
  'يوم هادي للتعافي': 'Easy recovery day',
  '٣ أيام جيم': '3 gym days',
  'Push / Pull / Legs: السبت، الاتنين، الأربع': 'Push / Pull / Legs: Saturday, Monday, Wednesday',
  '٥ أيام: ٣ جيم + ٢ بيت': '5 days: 3 gym + 2 home',
  'جيم Push / Pull / Legs: السبت، الاتنين، الخميس. بيت: الأحد، الأربع': 'Gym Push / Pull / Legs: Saturday, Monday, Thursday. Home: Sunday, Wednesday',
  '٥ أيام جيم': '5 gym days',
  'دفع، سحب، رجل، علوي، سفلي': 'Push, pull, legs, upper, lower',
  'ضهر مفرود وصدر لفوق': 'Back straight, chest up',
  'الركب في اتجاه صوابع الرجل': 'Knees in line with your toes',
  'النزول ببطء لحد ما الفخد يوازي الأرض': 'Lower slowly until thighs are parallel to the floor',
  'نفس قبل النزول وزفير مع الطلوع': 'Breathe in before lowering, breathe out on the way up',
  'ضهر لازق في المسند طول الوقت': 'Back pressed against the pad the whole time',
  'الرجلين بعرض الكتف على المنصة': 'Feet shoulder-width apart on the platform',
  'من غير قفل الركبة فوق': 'Don\'t lock your knees at the top',
  'النزول ببطء والدفع من الكعب': 'Lower slowly and push through your heels',
  'الدقن لتحت والضلوع مقفولة': 'Chin tucked, ribs down',
  'الدفع من الكعب': 'Push through your heels',
  'عصر المؤخرة ثانية فوق': 'Squeeze your glutes for a second at the top',
  'من غير تقويس أسفل الضهر': 'Don\'t arch your lower back',
  'ضهر مفرود طول الحركة': 'Back straight throughout the movement',
  'الحوض لورا والركبة مثنية خفيف': 'Hips back, knees slightly bent',
  'الدمبل قريب من الرجل': 'Dumbbells close to your legs',
  'الطلوع بعصر المؤخرة': 'Come up by squeezing your glutes',
  'الحوض لازق في الماكينة': 'Hips pressed against the machine',
  'الثني لآخر المدى وثبات ثانية': 'Curl to full range and hold for a second',
  'الرجوع ببطء من غير خبط': 'Return slowly without letting the weight slam',
  'من غير مرجحة الجسم': 'Don\'t swing your body',
  'الركبة على محور الماكينة': 'Knees lined up with the machine\'s pivot',
  'الفرد لفوق وعصر الفخد ثانية': 'Extend up and squeeze your thighs for a second',
  'النزول ببطء': 'Lower slowly',
  'ضهر لازق في المسند': 'Back against the pad',
  'ضهر مفرود على المسند': 'Back straight against the pad',
  'الفتح بتحكم لآخر المدى': 'Open with control to full range',
  'الرجوع ببطء من غير خبط الوزن': 'Return slowly without slamming the weight',
  'زفير مع الفتح': 'Breathe out as you open',
  'جذع مفرود والبطن مشدودة': 'Torso upright, core tight',
  'خطوة واسعة والركبتين على ٩٠ درجة': 'Long step, both knees at 90 degrees',
  'الركبة الأمامية فوق مشط الرجل': 'Front knee over the middle of your foot',
  'الدفع من كعب الرجل القدام': 'Push through the heel of your front foot',
  'الطلوع لأعلى نقطة على المشط': 'Rise to the highest point on the balls of your feet',
  'ثبات ثانية فوق': 'Hold for a second at the top',
  'النزول ببطء لآخر مطّة': 'Lower slowly into a full stretch',
  'الركبة مفرودة من غير قفل': 'Knees straight but not locked',
  'لوحين الكتف مضمومين لورا': 'Shoulder blades pulled back together',
  'الكوع زاوية ٤٥ درجة من الجسم': 'Elbows at 45 degrees from your body',
  'النزول ببطء لحد الصدر': 'Lower slowly to your chest',
  'زفير مع الدفع لفوق': 'Breathe out as you press up',
  'المقابض على مستوى نص الصدر': 'Handles at mid-chest height',
  'الدفع من غير قفل الكوع': 'Press without locking your elbows',
  'الرجوع ببطء مع شهيق': 'Return slowly while breathing in',
  'الكوع مثني خفيف وثابت': 'Elbows slightly bent and fixed',
  'الضم قدام الصدر وعصر ثانية': 'Bring together in front of your chest and squeeze for a second',
  'الفتح ببطء لحد مطّة مريحة': 'Open slowly to a comfortable stretch',
  'الكتف لتحت بعيد عن الودن': 'Shoulders down, away from your ears',
  'صدر لفوق وميلة بسيطة لورا': 'Chest up, leaning back slightly',
  'السحب لأعلى الصدر بالكوع': 'Pull to your upper chest, leading with your elbows',
  'الكتف لتحت قبل السحب': 'Shoulders down before you pull',
  'الطلوع ببطء لفرد كامل': 'Return up slowly to full extension',
  'ضهر مفرود من غير مرجحة': 'Back straight, no swinging',
  'السحب لحد البطن': 'Pull to your stomach',
  'ضم لوحين الكتف في الآخر': 'Squeeze your shoulder blades together at the end',
  'الرجوع ببطء مع فرد الدراع': 'Return slowly, straightening your arms',
  'ضهر مفرود وموازي للأرض': 'Back straight and parallel to the floor',
  'السحب بالكوع ناحية الوسط': 'Pull your elbow toward your waist',
  'من غير لف الجذع': 'Don\'t twist your torso',
  'النزول ببطء لفرد كامل': 'Lower slowly to full extension',
  'البطن مشدودة من غير تقويس': 'Core tight, no arching',
  'الدفع لفوق من غير خبط الدمبل': 'Press up without clanking the dumbbells',
  'النزول ببطء لمستوى الودن': 'Lower slowly to ear level',
  'وزن خفيف وحركة متحكمة': 'Light weight, controlled movement',
  'الرفع لحد مستوى الكتف بس': 'Raise only to shoulder height',
  'الكوع مثني خفيف': 'Elbows slightly bent',
  'النزول ببطء من غير مرجحة': 'Lower slowly without swinging',
  'الحبل على مستوى الوش': 'Rope at face height',
  'السحب ناحية الجبهة والكوع عالي': 'Pull toward your forehead, elbows high',
  'ضم لوحين الكتف ثانية': 'Squeeze your shoulder blades for a second',
  'الرجوع ببطء': 'Return slowly',
  'الكوع ثابت جنب الجسم': 'Elbows fixed at your sides',
  'الرفع من غير مرجحة الضهر': 'Lift without swinging your back',
  'عصر البايسبس فوق': 'Squeeze your biceps at the top',
  'الكوع لازق في الجنب': 'Elbows pinned to your sides',
  'السحب لفوق وعصر ثانية': 'Pull up and squeeze for a second',
  'جسم ثابت من غير ميلان': 'Body still, no leaning',
  'الفرد لتحت لآخر المدى': 'Extend down to full range',
  'عصر الترايسبس ثانية': 'Squeeze your triceps for a second',
  'الطلوع ببطء لحد ٩٠ درجة': 'Return up slowly to 90 degrees',
  'البنش على ميل ٣٠ درجة تقريباً': 'Bench at about a 30-degree incline',
  'لوحين الكتف مضمومين': 'Shoulder blades pulled together',
  'النزول ببطء لأعلى الصدر': 'Lower slowly to your upper chest',
  'المقابض على مستوى أعلى الصدر': 'Handles at upper-chest height',
  'المقابض على مستوى الكتف': 'Handles at shoulder height',
  'الدفع لفوق من غير قفل الكوع': 'Press up without locking your elbows',
  'النزول ببطء مع شهيق': 'Lower slowly while breathing in',
  'الكيبل من تحت ومن ورا الجسم': 'Cable low and behind your body',
  'الرفع لحد مستوى الكتف': 'Raise to shoulder height',
  'الكوع ثابت وقريب من الراس': 'Elbows fixed and close to your head',
  'الفرد لقدام وفوق لآخر المدى': 'Extend forward and up to full range',
  'الرجوع ببطء لمطّة كاملة': 'Return slowly into a full stretch',
  'السحب لحد الدقن فوق المسكة': 'Pull until your chin is over the handles',
  'جسم ثابت من غير مرجحة': 'Body still, no swinging',
  'الصدر لازق في المسند': 'Chest against the pad',
  'السحب بالكوع لورا': 'Pull your elbows back',
  'الرجوع ببطء لفرد كامل': 'Return slowly to full extension',
  'دراع مفرود والكوع مثني خفيف': 'Arms straight, elbows slightly bent',
  'السحب لحد الفخد': 'Pull down to your thighs',
  'ميلة بسيطة لقدام وضهر مفرود': 'Lean forward slightly, back straight',
  'الطلوع ببطء لمستوى الراس': 'Return up slowly to head height',
  'الفتح لورا بالكوع مثني خفيف': 'Open backward with elbows slightly bent',
  'من غير ما الكتف يطلع لفوق': 'Don\'t let your shoulders shrug up',
  'الكف ناحية الجسم طول الحركة': 'Palms facing your body throughout',
  'الرفع من غير مرجحة': 'Lift without swinging',
  'الرجلين بعرض الكتف': 'Feet shoulder-width apart',
  'النزول ببطء لحد ٩٠ درجة': 'Lower slowly to 90 degrees',
  'الدفع من الكعب من غير قفل الركبة': 'Push through your heels without locking your knees',
  'النزول عمودي لتحت': 'Lower straight down',
  'الطلوع بالدفع من الرجل القدام': 'Come up by pushing through your front leg',
  'المشط على الحافة والكعب حر': 'Balls of your feet on the edge, heels free',
  'الطلوع لأعلى نقطة وثبات ثانية': 'Rise to the highest point and hold for a second',
  'حركة كاملة من غير نط': 'Full range of motion, no bouncing',
  'ضهر مفرود والبطن مشدودة': 'Back straight, core tight',
  'الرجل لورا بعصر المؤخرة': 'Leg back, squeezing your glutes',
  'الكوع تحت الكتف': 'Elbows under your shoulders',
  'الجسم خط مستقيم من الراس للكعب': 'Body in a straight line from head to heels',
  'البطن والمؤخرة مشدودين': 'Core and glutes tight',
  'نفس منتظم من غير كتم': 'Breathe steadily, don\'t hold your breath',
  'أسفل الضهر لازق في الأرض': 'Lower back pressed into the floor',
  'دراع ورجل عكس بعض ببطء': 'Opposite arm and leg, slowly',
  'زفير مع فرد الرجل': 'Breathe out as you extend your leg',
  'حركة بطيئة ومتحكمة': 'Slow, controlled movement',
  'إحماء ٥ دقايق مشي الأول': 'Warm up with 5 minutes of walking first',
  'جري سريع قصير وبعده مشي للراحة': 'Short fast runs with walking breaks in between',
  'جسم مفرود من غير مسك المشاية': 'Body upright without holding the treadmill',
  'تهدئة بمشي في الآخر': 'Cool down with a walk at the end',
  'الكرسي على مستوى الحوض': 'Seat at hip height',
  'الركبة مثنية خفيف تحت': 'Knee slightly bent at the bottom',
  'ضهر مفرود والكتف مرتاح': 'Back straight, shoulders relaxed',
  'سرعة ثابتة ونفس منتظم': 'Steady pace, steady breathing',
  'ميل متوسط وسرعة مريحة': 'Moderate incline, comfortable speed',
  'خطوات طبيعية من الكعب للمشط': 'Natural steps from heel to toe',
  'نفس منتظم يسمح بالكلام': 'Steady breathing that still lets you talk',
  'الحوض لورا كأنه قعدة على كرسي': 'Hips back as if sitting in a chair',
  'النزول ببطء والطلوع بالكعب': 'Lower slowly and come up through your heels',
  'الرجلين بعرض الكتف قدام الكرسي': 'Feet shoulder-width apart in front of the chair',
  'القعدة ببطء من غير رمي الجسم': 'Sit down slowly without dropping',
  'القومة بالدفع من الكعب': 'Stand up by pushing through your heels',
  'الدراعات قدام للتوازن': 'Arms forward for balance',
  'الكعب قريب من المؤخرة': 'Heels close to your glutes',
  'رفع الحوض بعصر المؤخرة': 'Lift your hips by squeezing your glutes',
  'النزول ببطء من غير تقويس': 'Lower slowly without arching',
  'خطوة لورا والجذع مفرود': 'Step back with your torso upright',
  'الركبتين على ٩٠ درجة': 'Both knees at 90 degrees',
  'الوزن على كعب الرجل القدام': 'Weight on the heel of your front foot',
  'الرجوع بتحكم ومسك كرسي لو محتاج': 'Return with control, holding a chair if needed',
  'الإيدين بعرض الكتف على الحافة': 'Hands shoulder-width apart on the edge',
  'الجسم خط مستقيم': 'Body in a straight line',
  'النزول ببطء وزفير مع الدفع': 'Lower slowly, breathe out as you push',
  'الأستك مربوط ورا الضهر': 'Band anchored behind your back',
  'الدفع لقدام على مستوى الصدر': 'Press forward at chest height',
  'البطن مشدودة والضهر مفرود': 'Core tight, back straight',
  'ميلة لقدام وضهر مفرود': 'Lean forward with a straight back',
  'ضم لوحين الكتف فوق': 'Squeeze your shoulder blades at the top',
  'قعدة والرجلين مفرودين والأستك حوالين المشط': 'Sit with legs straight and the band around your feet',
  'ضهر مفرود من غير ميلان لورا': 'Back straight without leaning back',
  'السحب لحد البطن وضم الكتف': 'Pull to your stomach and squeeze your shoulder blades',
  'الدفع لفوق فوق الراس': 'Press up overhead',
  'زفير مع الدفع': 'Breathe out as you press',
  'الإيدين تحت الكتف والركب تحت الحوض': 'Hands under shoulders, knees under hips',
  'دراع ورجل عكس بعض لقدام ولورا': 'Opposite arm and leg reach forward and back',
  'ضهر مفرود من غير لف الحوض': 'Back straight without rotating your hips',
  'ثبات ثانيتين والرجوع ببطء': 'Hold for 2 seconds and return slowly',
  'المشط على السلمة والكعب برا': 'Balls of your feet on the step, heels off',
  'مسك الحيطة أو الدرابزين للتوازن': 'Hold the wall or railing for balance',
  'النزول ببطء تحت مستوى السلمة': 'Lower slowly below the level of the step',
  'نزول خفيف على المشط': 'Land softly on the balls of your feet',
  'الدراعات فوق والرجلين مفتوحين مع بعض': 'Arms up and feet apart at the same time',
  'ركب مثنية خفيف': 'Knees slightly bent',
  'نفس منتظم وإيقاع ثابت': 'Steady breathing and a steady rhythm',
  'الإيدين تحت الكتف': 'Hands under your shoulders',
  'الجسم خط مستقيم والحوض ثابت': 'Body in a straight line, hips steady',
  'الركبة ناحية الصدر بالتبادل': 'Alternate knees toward your chest',
  'سرعة مع الحفاظ على الشكل': 'Speed while keeping good form',
  'جسم مفرود والبطن مشدودة': 'Body upright, core tight',
  'رفع الركبة لمستوى الوسط': 'Raise your knees to waist height',
  'الدراعات تتحرك مع الرجل': 'Arms move with your legs',
  'نفس منتظم وإيقاع سريع': 'Steady breathing and a quick rhythm',
  'جسم مفرود والكتف مرتاح': 'Body upright, shoulders relaxed',
  'خطوات سريعة من الكعب للمشط': 'Quick steps from heel to toe',
  'الدراعات تتمرجح طبيعي': 'Arms swing naturally',
  'نفس يسمح بالكلام بصعوبة بسيطة': 'Breathing that lets you talk, just barely',
  'الرجلين أوسع من الكتف والصوابع لبرا': 'Feet wider than shoulders, toes turned out',
  'الزجاجة متدلية بين الرجلين': 'Bottle hanging between your legs',
  'الركب في اتجاه الصوابع': 'Knees in line with your toes',
  'النزول ببطء وضهر مفرود': 'Lower slowly with a straight back',
  'رفع الرجل لورا بعصر المؤخرة': 'Lift your leg back by squeezing your glutes',
  'الجسم على خط واحد على الجنب': 'Body in one line on your side',
  'رفع الرجل لفوق والصوابع لقدام': 'Lift your leg up with toes pointing forward',
  'من غير ميلان الحوض لورا': 'Don\'t let your hips roll back',
  'كرسي ثابت ومسنود على الحيطة': 'Sturdy chair braced against the wall',
  'الضهر قريب من حافة الكرسي': 'Back close to the edge of the chair',
  'النزول لحد ٩٠ درجة في الكوع': 'Lower until your elbows reach 90 degrees',
  'الكوع تحت الكتف مباشرة': 'Elbow directly under your shoulder',
  'الركب مثنية والحوض لفوق': 'Knees bent, hips up',
  'الجسم خط مستقيم من الراس للركبة': 'Body in a straight line from head to knees',
  'خطوة لجنب بدل النط': 'Step to the side instead of jumping',
  'الدراعات لفوق مع كل خطوة': 'Arms up with each step',
  'إيقاع ثابت ونفس منتظم': 'Steady rhythm, steady breathing',
  'ركب مرتاحة من غير قفل': 'Relaxed knees, not locked',
  'حركات بطيئة من غير شد زيادة': 'Slow movements without overstretching',
  'ثبات ٢٠-٣٠ ثانية في كل مطّة': 'Hold each stretch for 20-30 seconds',
  'نفس عميق مع كل مطّة': 'Breathe deeply with each stretch',
  'من غير ألم، مطّة مريحة بس': 'No pain, just a comfortable stretch',
  'قعدة مريحة وضهر مفرود': 'Sit comfortably with a straight back',
  'شهيق من الأنف ٤ عدات': 'Breathe in through your nose for 4 counts',
  'البطن تطلع مع الشهيق': 'Belly rises as you breathe in',
  'زفير بطيء من البوق ٦ عدات': 'Breathe out slowly through your mouth for 6 counts',
};
