// English for Arabic foods data text. Keys are the exact Arabic strings from the data files.
export const EN_FOODS: Record<string, string> = {
  'حصة': 'Serving',
  "فطار": "Breakfast",
  "عيش ونشويات": "Bread & starches",
  "بروتين": "Protein",
  "أكل بيتي": "Home cooking",
  "أكل برا وفاست فود": "Eating out & fast food",
  "خضار وسلطات": "Vegetables & salads",
  "فاكهة": "Fruit",
  "سناكس وحلويات": "Snacks & sweets",
  "مشروبات": "Drinks",
  "منتجات من السوبر ماركت": "Supermarket products",
  "زيوت وصوصات": "Oils & sauces",
  "فول مدمس": "Ful medames (fava beans)",
  "فول بالزيت الحار": "Ful with hot oil",
  "فول بالطحينة": "Ful with tahini",
  "فول إسكندراني": "Ful Eskandarani (Alexandrian-style fava beans)",
  "فول بالسجق": "Ful with sausage (sogo')",
  "طعمية": "Taameya (Egyptian falafel)",
  "ساندوتش طعمية": "Taameya sandwich",
  "ساندوتش فول": "Ful sandwich",
  "بيضة مسلوقة": "Boiled egg",
  "بيضة مقلية": "Fried egg",
  "أومليت": "Omelette",
  "بياض بيض مسلوق": "Boiled egg whites",
  "شكشوكة": "Shakshuka",
  "جبنة قريش": "Areesh cheese (cottage cheese)",
  "جبنة قريش لايت": "Light areesh cheese",
  "جبنة رومي": "Roumi cheese",
  "جبنة فيتا": "Feta cheese",
  "جبنة شيدر": "Cheddar cheese",
  "جبنة مثلثات (نستو)": "Cheese triangles (Nesto)",
  "جبنة كريمي": "Cream cheese",
  "جبنة ميش": "Mish (aged cheese)",
  "لبنة": "Labneh",
  "قشطة": "Eshta (clotted cream)",
  "فطير مشلتت": "Feteer meshaltet (flaky pastry)",
  "فطير مشلتت بالعسل والقشطة": "Feteer meshaltet with honey and eshta",
  "شوفان باللبن": "Oats with milk",
  "شوفان بالمية والموز": "Oats with water and banana",
  "كورن فليكس باللبن": "Cornflakes with milk",
  "حلاوة طحينية": "Halawa (tahini halva)",
  "بليلة باللبن": "Belila (wheat berries) with milk",
  "بذور شيا": "Chia seeds",
  "بذر كتان مطحون": "Ground flaxseed",
  "عيش بلدي": "Baladi bread",
  "عيش سن": "Whole-wheat bran bread (eish sen)",
  "عيش شامي": "Shami bread (pita)",
  "عيش فينو": "Fino bread roll",
  "توست أبيض": "White toast",
  "توست بني": "Brown toast",
  "توست حبوب كاملة": "Whole-grain toast",
  "توست شوفان": "Oat toast",
  "عيش شوفان": "Oat bread",
  "بقسماط": "Rusks (bo'somat)",
  "عيش تورتيلا": "Tortilla bread",
  "رز أبيض": "White rice",
  "رز بالشعرية": "Rice with vermicelli",
  "رز بني": "Brown rice",
  "رز بسمتي": "Basmati rice",
  "رز معمر": "Rice mammar (baked rice)",
  "كينوا": "Quinoa",
  "برغل": "Bulgur",
  "فريك": "Freekeh",
  "مكرونة مسلوقة": "Boiled pasta",
  "مكرونة بالصلصة": "Pasta with tomato sauce",
  "مكرونة قمح كامل": "Whole-wheat pasta",
  "بطاطس مسلوقة": "Boiled potatoes",
  "بطاطس محمرة بيتي": "Home-fried potatoes",
  "بطاطس بالفرن": "Oven-baked potatoes",
  "كسكسي بالسكر واللبن": "Couscous with sugar and milk",
  "صدر فراخ مشوي": "Grilled chicken breast",
  "ربع فرخة مشوية": "Grilled quarter chicken",
  "فراخ بانيه": "Chicken pane (breaded cutlet)",
  "استربس فراخ": "Chicken strips",
  "شيش طاووق": "Shish tawook",
  "كبدة فراخ": "Chicken liver",
  "لحمة مسلوقة": "Boiled beef",
  "ستيك لحمة": "Beef steak",
  "كفتة مشوية": "Grilled kofta",
  "ريش ضاني": "Lamb chops",
  "كبدة بقري مشوية": "Grilled beef liver",
  "سجق": "Sausage (sogo')",
  "بسطرمة": "Pastirma",
  "بط محمر": "Roast duck",
  "أرانب مسلوقة": "Boiled rabbit",
  "سمك بلطي مشوي": "Grilled tilapia (bolti)",
  "سمك بلطي مقلي": "Fried tilapia (bolti)",
  "بوري مشوي": "Grilled mullet (bouri)",
  "فيليه موسى مقلي": "Fried sole fillet",
  "سالمون مشوي": "Grilled salmon",
  "سردين مشوي": "Grilled sardines",
  "سردين علبة بالزيت": "Canned sardines in oil",
  "تونة بالزيت": "Tuna in oil",
  "تونة بالمية": "Tuna in water",
  "جمبري مشوي": "Grilled shrimp",
  "جمبري بانيه مقلي": "Fried breaded shrimp",
  "رنجة": "Renga (smoked herring)",
  "فسيخ": "Feseekh (fermented fish)",
  "عدس بجبة": "Brown lentils",
  "حمص مسلوق": "Boiled chickpeas",
  "فول نابت": "Sprouted fava beans (ful nabet)",
  "بيصارة": "Bessara (fava bean dip)",
  "زبادي يوناني لايت": "Light Greek yogurt",
  "بروتين واي": "Whey protein",
  "ملوخية": "Molokhia",
  "بامية باللحمة": "Okra with meat",
  "فاصوليا خضرا باللحمة": "Green beans with meat",
  "بسلة بالجزر واللحمة": "Peas with carrots and meat",
  "بطاطس بالصلصة واللحمة": "Potatoes in tomato sauce with meat",
  "سبانخ باللحمة": "Spinach with meat",
  "قلقاس بالخضرة": "Taro (colcas) with greens",
  "كوسة بالبشاميل": "Zucchini with béchamel",
  "مسقعة": "Mesaqaa (Egyptian moussaka)",
  "محشي كرنب": "Stuffed cabbage (mahshi)",
  "محشي ورق عنب": "Stuffed grape leaves (mahshi)",
  "محشي كوسة وباذنجان": "Stuffed zucchini and eggplant (mahshi)",
  "محشي فلفل وطماطم": "Stuffed peppers and tomatoes (mahshi)",
  "ممبار": "Mombar (stuffed sausage casings)",
  "مكرونة بشاميل": "Macarona béchamel",
  "فتة باللحمة": "Fatta with meat",
  "طاجن فراخ بالخضار": "Chicken and vegetable tagine",
  "كفتة داوود باشا": "Kofta Dawood Basha (meatballs in sauce)",
  "كبدة اسكندراني": "Kebda Eskandarani (Alexandrian liver)",
  "كوارع": "Kawareh (trotters)",
  "حمام محشي فريك": "Pigeon stuffed with freekeh",
  "رقاق باللحمة": "Roqaq with meat",
  "جلاش باللحمة": "Goulash pastry with meat",
  "كبيبة": "Kibbeh",
  "سمك سنجاري بالفرن": "Baked fish Singari",
  "شوربة عدس": "Lentil soup",
  "شوربة لسان عصفور": "Orzo soup (lesan asfour)",
  "شوربة خضار": "Vegetable soup",
  "لوبيا ناشفة بالصلصة": "Dried black-eyed peas in tomato sauce",
  "كشري": "Koshari",
  "ساندوتش كبدة اسكندراني": "Alexandrian liver sandwich",
  "ساندوتش سجق": "Sausage sandwich",
  "حواوشي": "Hawawshi (spiced meat in bread)",
  "شاورما فراخ": "Chicken shawarma",
  "شاورما لحمة": "Beef shawarma",
  "وجبة شاورما عربي": "Arabi shawarma meal",
  "ساندوتش كفتة": "Kofta sandwich",
  "ساندوتش تونة": "Tuna sandwich",
  "فطير حادق بالجبنة": "Savory feteer with cheese",
  "فطير باللحمة المفرومة": "Feteer with minced meat",
  "بيتزا مارجريتا": "Margherita pizza",
  "بيتزا بيبروني": "Pepperoni pizza",
  "بيج ماك": "Big Mac",
  "تشيز برجر": "Cheeseburger",
  "ساندوتش فراخ كرسبي": "Crispy chicken sandwich",
  "قطعة فراخ كرسبي (كنتاكي)": "Crispy chicken piece (KFC)",
  "ناجتس": "Nuggets",
  "فرايز": "Fries",
  "هوت دوج": "Hot dog",
  "كريب فراخ بانيه": "Chicken pane crepe",
  "سوشي": "Sushi",
  "كبسة فراخ": "Chicken kabsa",
  "لحمة مندي": "Lamb mandi",
  "سلطة سيزر بالفراخ": "Chicken Caesar salad",
  "مكرونة ألفريدو بالفراخ": "Chicken Alfredo pasta",
  "سلطة خضرا بلدي": "Baladi green salad",
  "سلطة طحينة": "Tahini salad",
  "بابا غنوج": "Baba ghanoush",
  "سلطة زبادي بالخيار": "Yogurt and cucumber salad",
  "تبولة": "Tabbouleh",
  "فتوش": "Fattoush",
  "خيار": "Cucumber",
  "طماطم": "Tomato",
  "جزر": "Carrot",
  "خس": "Lettuce",
  "جرجير": "Arugula (gargeer)",
  "فلفل رومي ألوان": "Colored bell peppers",
  "بروكلي مسلوق": "Boiled broccoli",
  "كوسة سوتيه": "Sautéed zucchini",
  "سبانخ سوتيه": "Sautéed spinach",
  "بسلة مسلوقة": "Boiled peas",
  "باذنجان مشوي": "Grilled eggplant",
  "باذنجان مقلي": "Fried eggplant",
  "قرنبيط مقلي": "Fried cauliflower",
  "بطاطا مشوية": "Roasted sweet potato",
  "ذرة مشوي": "Grilled corn",
  "أفوكادو": "Avocado",
  "مخلل مشكل": "Mixed pickles",
  "زيتون أخضر": "Green olives",
  "زيتون أسود": "Black olives",
  "زيتون مخلل": "Pickled olives",
  "مخلل مشكل (طرشي)": "Mixed pickles (torshi)",
  "جوافة": "Guava",
  "مانجا": "Mango",
  "بطيخ": "Watermelon",
  "شمام": "Cantaloupe",
  "فراولة": "Strawberries",
  "عنب": "Grapes",
  "تين": "Figs",
  "رمان": "Pomegranate",
  "كاكا": "Persimmon (kaka)",
  "يوسفي": "Mandarin",
  "برتقان": "Orange",
  "كمثرى": "Pear",
  "خوخ": "Peach",
  "مشمش": "Apricot",
  "تفاح": "Apple",
  "موز": "Banana",
  "أناناس": "Pineapple",
  "كيوي": "Kiwi",
  "بلح سيوي": "Siwi dates",
  "بلح مجدول": "Medjool dates",
  "بلح أمهات": "Amhat dates",
  "مشمش مجفف": "Dried apricots",
  "زبيب": "Raisins",
  "سلطة فواكه بالقشطة": "Fruit salad with eshta",
  "بسبوسة": "Basbousa",
  "بسبوسة بالقشطة": "Basbousa with eshta",
  "كنافة بالقشطة": "Kunafa with eshta",
  "كنافة بالمكسرات": "Kunafa with nuts",
  "قطايف بالمكسرات": "Qatayef with nuts",
  "أم علي": "Om Ali",
  "رز بلبن": "Roz bel laban (rice pudding)",
  "مهلبية": "Mahalabia (milk pudding)",
  "كريم كراميل": "Crème caramel",
  "جلاش بالمكسرات": "Goulash pastry with nuts",
  "بلح الشام": "Balah el sham (fried dough fingers)",
  "لقمة القاضي": "Luqmet el qadi (honey dough balls)",
  "كحك بالعجمية": "Kahk with agameya (Eid cookies)",
  "بسكويت العيد": "Eid biscuits",
  "كيكة بيتي": "Homemade cake",
  "تورتة شوكولاتة": "Chocolate cake",
  "تشيز كيك": "Cheesecake",
  "كريب نوتيلا": "Nutella crepe",
  "آيس كريم": "Ice cream",
  "ماك فلوري": "McFlurry",
  "سمسمية": "Sesame brittle (semsemeya)",
  "فولية": "Peanut brittle (fouleya)",
  "شوكولاتة باللبن": "Milk chocolate",
  "شوكولاتة دارك ٧٠٪": "Dark chocolate 70%",
  "سوداني محمص": "Roasted peanuts",
  "لوز": "Almonds",
  "عين جمل": "Walnuts",
  "فستق": "Pistachios",
  "لب أبيض": "White seeds (lib abyad)",
  "ترمس": "Lupini beans (termes)",
  "حمص الشام": "Roasted chickpeas (homs el sham)",
  "فشار": "Popcorn",
  "شاي بمعلقتين سكر": "Tea with 2 spoons of sugar",
  "شاي من غير سكر": "Tea without sugar",
  "شاي بلبن": "Tea with milk",
  "شاي أخضر": "Green tea",
  "كركديه بالسكر": "Karkade (hibiscus) with sugar",
  "نسكافيه ٣ في ١": "Nescafé 3-in-1",
  "نسكافيه بلبن من غير سكر": "Nescafé with milk, no sugar",
  "قهوة تركي سادة": "Turkish coffee, no sugar",
  "قهوة تركي مظبوط": "Turkish coffee, medium sugar",
  "كابتشينو": "Cappuccino",
  "لاتيه": "Latte",
  "فرابتشينو": "Frappuccino",
  "سحلب بالمكسرات": "Sahlab with nuts",
  "لبن كامل الدسم": "Full-fat milk",
  "بروتين شيك باللبن": "Protein shake with milk",
  "عصير برتقان فريش": "Fresh orange juice",
  "عصير مانجا بالسكر": "Mango juice with sugar",
  "عصير قصب": "Sugarcane juice",
  "فراولة باللبن": "Strawberry milk",
  "سموذي فواكه بالزبادي": "Fruit and yogurt smoothie",
  "سوبيا": "Sobia (coconut rice drink)",
  "خروب": "Carob drink (kharoub)",
  "تمر هندي": "Tamarind drink",
  "عرقسوس": "Licorice drink (erq sous)",
  "قمر الدين": "Qamar el din (apricot drink)",
  "بيبسي": "Pepsi",
  "كوكاكولا": "Coca-Cola",
  "سفن أب": "7Up",
  "ميرندا برتقان": "Mirinda Orange",
  "شويبس": "Schweppes",
  "ريد بول": "Red Bull",
  "بيبسي دايت": "Diet Pepsi",
  "كوكاكولا زيرو": "Coca-Cola Zero",
  "سفن أب دايت": "Diet 7Up",
  "ريد بول شوجر فري": "Red Bull Sugarfree",
  "مية": "Water",
  "شيبسي": "Chipsy",
  "شيبسي كيس كبير": "Chipsy, large bag",
  "تورتيلا شيبس": "Tortilla chips",
  "بسكويت شاي سادة": "Plain tea biscuits",
  "بسكويت محشي شوكولاتة": "Chocolate-filled biscuits",
  "كرواسون معلب": "Packaged croissant",
  "مولتو": "Molto",
  "توينكز": "Twix",
  "كيت كات": "KitKat",
  "سنيكرز": "Snickers",
  "معمول بالتمر": "Date maamoul",
  "إندومي": "Indomie",
  "لانشون لحمة": "Beef luncheon meat",
  "لانشون فراخ": "Chicken luncheon meat",
  "صدر رومي مدخن": "Smoked turkey breast",
  "بانيه مجمد": "Frozen breaded chicken (pane)",
  "برجر لحمة مجمد": "Frozen beef burger",
  "جبنة سايحة": "Processed cheese spread",
  "زبادي سادة": "Plain yogurt",
  "زبادي لايت": "Light yogurt",
  "زبادي بالفواكه": "Fruit yogurt",
  "لبن رايب": "Laban rayeb (cultured milk)",
  "لبن بالشوكولاتة": "Chocolate milk",
  "عصير كرتونة (جهينة)": "Boxed juice (Juhayna)",
  "بار بروتين": "Protein bar",
  "شوفان سريع بالفواكه": "Instant oats with fruit",
  "جرانولا": "Granola",
  "ذرة حلوة علبة": "Canned sweet corn",
  "فول مدمس معلب": "Canned ful medames",
  "رايس كيك": "Rice cakes",
  "زيت زيتون": "Olive oil",
  "زيت طعام": "Cooking oil",
  "زبدة": "Butter",
  "سمنة بلدي": "Samna baladi (ghee)",
  "سمنة نباتي": "Vegetable ghee",
  "مايونيز": "Mayonnaise",
  "كاتشب": "Ketchup",
  "صوص باربكيو": "BBQ sauce",
  "ثومية": "Toumeya (garlic sauce)",
  "صلصة طماطم": "Tomato paste",
  "طحينة خام": "Raw tahini",
  "زبدة فول سوداني": "Peanut butter",
  "عسل نحل": "Honey",
  "عسل أسود": "Molasses (black honey)",
  "مربى": "Jam",
  "نوتيلا": "Nutella",
  "سكر": "Sugar",
  "محلي صناعي": "Artificial sweetener",
  "طبق ٢٠٠ جم بزيت قليل": "Plate, 200 g, little oil",
  "طبق ٢٠٠ جم": "Plate, 200 g",
  "طبق ٢٠٠ جم بالطماطم والفلفل": "Plate, 200 g, with tomatoes and peppers",
  "طبق ٢٥٠ جم": "Plate, 250 g",
  "قرص ٣٠ جم": "1 disc, 30 g",
  "نص رغيف بلدي بالسلطة": "Half a baladi loaf with salad",
  "نص رغيف بلدي": "Half a baladi loaf",
  "حباية ٥٠ جم": "1 piece, 50 g",
  "حباية بمعلقة زيت صغيرة": "1 piece with a teaspoon of oil",
  "٢ بيضة": "2 eggs",
  "٣ بياض": "3 egg whites",
  "طاسة ٢ بيضة بالطماطم": "Pan, 2 eggs with tomatoes",
  "١٠٠ جم": "100 g",
  "شريحة ٣٠ جم": "1 slice, 30 g",
  "٥٠ جم": "50 g",
  "شريحة ٢٠ جم": "1 slice, 20 g",
  "مثلث ١٧ جم": "1 triangle, 17 g",
  "معلقة ٢٠ جم": "1 tablespoon, 20 g",
  "٣٠ جم": "30 g",
  "٢ معلقة ٤٠ جم": "2 tablespoons, 40 g",
  "قطعة ١٠٠ جم": "1 piece, 100 g",
  "قطعة ١٠٠ جم + معلقتين عسل وقشطة": "1 piece, 100 g + 2 tablespoons honey and eshta",
  "طبق ٤٠ جم شوفان + كوباية لبن": "Bowl, 40 g oats + 1 cup milk",
  "طبق ٤٠ جم شوفان + موزة": "Bowl, 40 g oats + 1 banana",
  "طبق ٣٠ جم + كوباية لبن": "Bowl, 30 g + 1 cup milk",
  "٢ معلقة ٣٠ جم": "2 tablespoons, 30 g",
  "طبق ٢٥٠ جم بمعلقة سكر": "Bowl, 250 g, with a spoon of sugar",
  "معلقة ١٢ جم": "1 tablespoon, 12 g",
  "معلقة ٧ جم": "1 tablespoon, 7 g",
  "رغيف ٩٠ جم": "1 loaf, 90 g",
  "رغيف ٨٠ جم": "1 loaf, 80 g",
  "رغيف ٦٠ جم": "1 loaf, 60 g",
  "رغيف صغير ٥٠ جم": "1 small loaf, 50 g",
  "شريحة ٢٥ جم": "1 slice, 25 g",
  "شريحة ٢٨ جم": "1 slice, 28 g",
  "شريحة ٣٢ جم": "1 slice, 32 g",
  "٣ صوابع ٣٠ جم": "3 sticks, 30 g",
  "كوباية مطبوخ ١٦٠ جم": "1 cup cooked, 160 g",
  "طاجن صغير ٢٥٠ جم": "Small tagine, 250 g",
  "كوباية مطبوخة ١٨٥ جم": "1 cup cooked, 185 g",
  "كوباية مطبوخ ١٨٠ جم": "1 cup cooked, 180 g",
  "كوباية مطبوخ ١٧٠ جم": "1 cup cooked, 170 g",
  "كوباية ١٤٠ جم": "1 cup, 140 g",
  "حباية متوسطة ١٧٠ جم": "1 medium piece, 170 g",
  "طبق ١٥٠ جم": "Plate, 150 g",
  "١٥٠ جم": "150 g",
  "ورك ٢٠٠ جم بالجلد": "1 leg, 200 g, with skin",
  "قطعة ١٢٠ جم": "1 piece, 120 g",
  "٥ قطع ١٥٠ جم": "5 pieces, 150 g",
  "سيخ ٢٠٠ جم": "1 skewer, 200 g",
  "٤ صوابع ١٥٠ جم": "4 fingers, 150 g",
  "٣ ريشات ١٥٠ جم": "3 chops, 150 g",
  "٣ شرايح ٣٠ جم": "3 slices, 30 g",
  "ربع بطة ٢٠٠ جم": "Quarter duck, 200 g",
  "سمكة ٢٥٠ جم (١٥٠ جم صافي)": "1 fish, 250 g (150 g net)",
  "سمكة ٢٥٠ جم": "1 fish, 250 g",
  "٢٠٠ جم صافي": "200 g net",
  "علبة ٩٠ جم صافي": "1 can, 90 g drained",
  "علبة ٨٥ جم صافي": "1 can, 85 g drained",
  "رنجة ١٠٠ جم صافي": "1 herring, 100 g net",
  "كوباية مطبوخ ١٩٠ جم": "1 cup cooked, 190 g",
  "كوباية ١٦٠ جم": "1 cup, 160 g",
  "طبق ٢٥٠ جم بالشوربة": "Bowl, 250 g, with broth",
  "علبة ١٧٠ جم": "1 tub, 170 g",
  "سكوب ٣٠ جم بالمية": "1 scoop, 30 g, with water",
  "قطعة ٢٥٠ جم": "1 piece, 250 g",
  "١٠ صوابع ٢٠٠ جم": "10 rolls, 200 g",
  "١٠ صوابع ١٥٠ جم": "10 rolls, 150 g",
  "٦ قطع ٢٢٠ جم": "6 pieces, 220 g",
  "٣ حبايات": "3 pieces",
  "٥ صوابع ١٥٠ جم": "5 pieces, 150 g",
  "طبق ٣٥٠ جم": "Plate, 350 g",
  "طبق ٣٠٠ جم": "Plate, 300 g",
  "حمامة": "1 pigeon",
  "قطعة ٢٠٠ جم": "1 piece, 200 g",
  "قطعة ١٥٠ جم": "1 piece, 150 g",
  "قطعة ٦٠ جم": "1 piece, 60 g",
  "علبة وسط ٣٥٠ جم": "Medium box, 350 g",
  "رغيف بلدي": "Baladi loaf",
  "ساندوتش سوري": "Syrian sandwich",
  "وجبة بالبطاطس والثومية": "Meal with fries and toumeya",
  "ربع فطيرة": "Quarter feteer",
  "شريحة ١٠٧ جم": "1 slice, 107 g",
  "شريحة ١١٠ جم": "1 slice, 110 g",
  "ساندوتش": "1 sandwich",
  "قطعة ورك": "1 thigh piece",
  "٦ قطع": "6 pieces",
  "علبة صغيرة ٨٠ جم": "Small box, 80 g",
  "كريب": "1 crepe",
  "٨ قطع": "8 pieces",
  "طبق بربع فرخة": "Plate with quarter chicken",
  "طبق": "1 plate",
  "حباية ١٠٠ جم": "1 piece, 100 g",
  "حباية ١٢٠ جم": "1 piece, 120 g",
  "حباية ٧٠ جم": "1 piece, 70 g",
  "طبق ١٠٠ جم": "Plate, 100 g",
  "حزمة ٥٠ جم": "1 bunch, 50 g",
  "حباية ١٥٠ جم": "1 piece, 150 g",
  "كوباية ١٥٠ جم": "1 cup, 150 g",
  "حباية ٢٠٠ جم": "1 piece, 200 g",
  "كوز (١٠٠ جم حبوب)": "1 cob (100 g kernels)",
  "نص حباية ٧٥ جم": "Half a piece, 75 g",
  "١٠ حبايات ٤٠ جم": "10 pieces, 40 g",
  "طبق صغير ١٠٠ جم": "Small plate, 100 g",
  "حباية متوسطة ٢٠٠ جم صافي": "1 medium piece, 200 g net",
  "شريحة ٣٠٠ جم": "1 slice, 300 g",
  "شريحة ٢٠٠ جم": "1 slice, 200 g",
  "٢ حباية ١٠٠ جم": "2 pieces, 100 g",
  "حباية (١٥٠ جم حبوب)": "1 piece (150 g seeds)",
  "حباية ١٦٠ جم": "1 piece, 160 g",
  "٢ حباية ١٥٠ جم": "2 pieces, 150 g",
  "حباية ١٨٠ جم": "1 piece, 180 g",
  "٣ حبايات ١٠٥ جم": "3 pieces, 105 g",
  "حباية متوسطة ١٢٠ جم": "1 medium piece, 120 g",
  "٣ حبايات ٢٥ جم": "3 pieces, 25 g",
  "حباية ٢٤ جم": "1 piece, 24 g",
  "٥ حبايات ٦٠ جم": "5 pieces, 60 g",
  "٥ حبايات ٣٥ جم": "5 pieces, 35 g",
  "معلقة كبيرة ٣٠ جم": "1 tablespoon, 30 g",
  "كوباية ٢٥٠ جم": "1 cup, 250 g",
  "قطعة ٨٠ جم": "1 piece, 80 g",
  "٢ قطعة مقلية": "2 fried pieces",
  "كوباية ٢٠٠ جم": "1 cup, 200 g",
  "علبة ١٢٠ جم": "1 tub, 120 g",
  "٢ قطعة ٦٠ جم": "2 pieces, 60 g",
  "٣ صوابع ٦٠ جم": "3 fingers, 60 g",
  "٦ حبات ٦٠ جم": "6 pieces, 60 g",
  "قطعة ٤٠ جم": "1 piece, 40 g",
  "٣ قطع ٣٠ جم": "3 pieces, 30 g",
  "بولة ٧٠ جم": "1 scoop, 70 g",
  "كوباية عادي": "Regular cup",
  "قطعة ٣٠ جم": "1 piece, 30 g",
  "لوح ٤٠ جم": "1 bar, 40 g",
  "٣ مربعات ٣٠ جم": "3 squares, 30 g",
  "حفنة ٣٠ جم": "1 handful, 30 g",
  "٢٣ حباية ٣٠ جم": "23 pieces, 30 g",
  "٣٠ جم صافي": "30 g shelled",
  "كوباية ١٠٠ جم": "1 cup, 100 g",
  "كوباية": "1 cup",
  "٣ كوبايات ٢٥ جم": "3 cups, 25 g",
  "كوباية بمعلقة سكر": "1 cup with a spoon of sugar",
  "كوباية من غير سكر": "1 cup without sugar",
  "كوباية ٢٥٠ مل": "1 cup, 250 ml",
  "كيس ١٨ جم": "1 sachet, 18 g",
  "فنجان": "1 small cup",
  "كوباية وسط ٣٥٠ مل": "Medium cup, 350 ml",
  "كوباية ٤٠٠ مل": "1 cup, 400 ml",
  "سكوب + كوباية لبن": "1 scoop + 1 cup milk",
  "كوباية ٣٠٠ مل": "1 cup, 300 ml",
  "كوباية ٣٠٠ مل من غير سكر": "1 cup, 300 ml, no sugar",
  "كانز ٣٣٠ مل": "1 can, 330 ml",
  "علبة ٢٥٠ مل": "1 pack, 250 ml",
  "كوباية أو إزازة": "1 glass or bottle",
  "كيس صغير ٣٥ جم": "Small bag, 35 g",
  "كيس ٨٠ جم": "1 bag, 80 g",
  "كيس ٤٠ جم": "1 bag, 40 g",
  "٤ قطع ٣٠ جم": "4 pieces, 30 g",
  "٣ قطع ٣٤ جم": "3 pieces, 34 g",
  "قطعة ٥٥ جم": "1 piece, 55 g",
  "باكو قطعتين ٧٧ جم": "Pack of 2, 77 g",
  "٤ صوابع ٤١ جم": "4 fingers, 41 g",
  "باكو ٥٠ جم": "1 pack, 50 g",
  "كيس ٧٥ جم": "1 pack, 75 g",
  "٣ شرايح ٥٠ جم": "3 slices, 50 g",
  "٣ قطع ١٠٠ جم مقلية": "3 pieces, 100 g, fried",
  "قرص ٧٠ جم": "1 patty, 70 g",
  "علبة ١٠٥ جم": "1 tub, 105 g",
  "علبة ٢٠٠ مل": "1 pack, 200 ml",
  "علبة ٢٣٥ مل": "1 pack, 235 ml",
  "بار ٦٠ جم": "1 bar, 60 g",
  "نص كوباية ٥٠ جم": "Half a cup, 50 g",
  "نص علبة ١٢٥ جم": "Half a can, 125 g",
  "نص علبة ٢٠٠ جم": "Half a can, 200 g",
  "٢ قطعة ١٨ جم": "2 pieces, 18 g",
  "معلقة كبيرة ١٤ جم": "1 tablespoon, 14 g",
  "معلقة كبيرة ١٧ جم": "1 tablespoon, 17 g",
  "معلقة كبيرة ١٥ جم": "1 tablespoon, 15 g",
  "معلقة كبيرة ١٦ جم": "1 tablespoon, 16 g",
  "معلقة كبيرة ٢١ جم": "1 tablespoon, 21 g",
  "معلقة كبيرة ٢٠ جم": "1 tablespoon, 20 g",
  "معلقة صغيرة ٥ جم": "1 teaspoon, 5 g",
  "كيس": "1 sachet",
  "أكلاتي": "My foods",
  "الكل": "All",
};
