// English for Arabic recipes data text. Keys are the exact Arabic strings from the data files.
export const EN_RECIPES: Record<string, string> = {
  // b_foul_oil
  "فول بزيت الزيتون والطماطم مع عيش سن": "Ful with olive oil & tomato and whole-wheat bread",
  "طبق فول ٢٠٠ جم + نص رغيف بلدي سن": "200 g ful plate + 1/2 whole-wheat baladi loaf",
  "٢٠٠ جم فول مدمس مسلوق في البيت": "200 g home-cooked ful medames (fava beans)",
  "١ معلقة صغيرة زيت زيتون": "1 tsp olive oil",
  "١ طماطماية مقطعة مكعبات": "1 tomato, diced",
  "نص بصلة خضرا مفرومة": "1/2 green onion, chopped",
  "كمون وملح خفيف وعصير نص ليمونة": "Cumin, a little salt and juice of 1/2 lemon",
  "نص رغيف عيش بلدي سن": "1/2 whole-wheat baladi loaf",
  "سخني الفول على نار هادية بشوية من مية السلق.": "Warm the ful over low heat with a little of its cooking water.",
  "اهرسيه هرس خفيف بالشوكة.": "Mash it lightly with a fork.",
  "ضيفي الكمون والملح الخفيف والليمون.": "Add the cumin, a little salt and the lemon.",
  "قطعي الطماطم والبصل الأخضر ورشيهم على الوش.": "Chop the tomato and green onion and scatter on top.",
  "رشي معلقة زيت الزيتون وقدميه مع نص الرغيف السن.": "Drizzle the spoon of olive oil and serve with the 1/2 whole-wheat loaf.",
  // b_egg_baladi
  "بيض مسلوق مع عيش بلدي سن وسلطة": "Boiled eggs with whole-wheat baladi bread and salad",
  "٢ بيضة + رغيف بلدي سن صغير + خضار": "2 eggs + 1 small whole-wheat baladi loaf + vegetables",
  "٢ بيضة": "2 eggs",
  "١ رغيف عيش بلدي سن صغير (٧٠ جم)": "1 small whole-wheat baladi loaf (70 g)",
  "١ خيارة": "1 cucumber",
  "١ طماطماية": "1 tomato",
  "رشة كمون وملح خفيف": "A pinch of cumin and a little salt",
  "حطي البيض في مية باردة وسيبيه يغلي.": "Put the eggs in cold water and bring to a boil.",
  "من أول الغليان سيبيه ٩ دقايق للسلق الكامل.": "Once boiling, cook 9 minutes for hard-boiled.",
  "قشري البيض تحت مية باردة.": "Peel the eggs under cold water.",
  "قطعي الخيار والطماطم شرايح.": "Slice the cucumber and tomato.",
  "قدمي البيض مع العيش السن والخضار ورشة كمون.": "Serve the eggs with the whole-wheat bread, vegetables and a pinch of cumin.",
  // b_shakshuka
  "شكشوكة بالخضار": "Vegetable shakshuka",
  "طاسة صغيرة ٢ بيضة": "Small pan, 2 eggs",
  "٢ طماطماية مبشورة": "2 tomatoes, grated",
  "نص فلفل رومي مقطع": "1/2 bell pepper, chopped",
  "ربع بصلة مفرومة": "1/4 onion, chopped",
  "كمون وفلفل أسود وملح خفيف": "Cumin, black pepper and a little salt",
  "شوحي البصل والفلفل في معلقة الزيت دقيقتين.": "Sauté the onion and pepper in the spoon of oil for 2 minutes.",
  "ضيفي الطماطم والتوابل وسيبيها تتسبك ٥ دقايق.": "Add the tomatoes and spices and simmer 5 minutes.",
  "اعملي حفرتين واكسري فيهم البيض.": "Make 2 wells and crack the eggs into them.",
  "غطي الطاسة على نار هادية لحد ما البياض يستوي.": "Cover the pan over low heat until the whites are set.",
  "قدميها سخنة مع خيار أو خس.": "Serve hot with cucumber or lettuce.",
  // b_oats_milk_fruit
  "شوفان بالحليب والفاكهة": "Oatmeal with milk and fruit",
  "بولة ٣٠٠ جم": "300 g bowl",
  "٥٠ جم شوفان": "50 g oats",
  "٢٠٠ مل لبن خالي أو قليل الدسم": "200 ml skim or low-fat milk",
  "١ موزة صغيرة مقطعة": "1 small banana, sliced",
  "٥٠ جم فراولة أو تفاح": "50 g strawberries or apple",
  "رشة قرفة": "A pinch of cinnamon",
  "حطي الشوفان مع اللبن في كسرولة صغيرة.": "Put the oats and milk in a small saucepan.",
  "قلبي على نار هادية ٤-٥ دقايق لحد ما يتقل.": "Stir over low heat 4-5 minutes until thick.",
  "ضيفي القرفة بدل السكر.": "Add cinnamon instead of sugar.",
  "صبيه في بولة ورصي الفاكهة فوقه.": "Pour into a bowl and top with the fruit.",
  // b_qareish_veg
  "جبنة قريش بالخضار وزيت الزيتون": "Qareish cheese with vegetables and olive oil",
  "١٥٠ جم قريش + نص رغيف سن": "150 g qareish + 1/2 whole-wheat loaf",
  "١٥٠ جم جبنة قريش": "150 g qareish cheese (Egyptian cottage cheese)",
  "١ طماطماية مقطعة صغير": "1 tomato, finely diced",
  "١ خيارة مقطعة صغير": "1 cucumber, finely diced",
  "ربع فلفل أخضر": "1/4 green pepper",
  "نعناع ناشف وكمون": "Dried mint and cumin",
  "نص رغيف بلدي سن": "1/2 whole-wheat baladi loaf",
  "فتتي الجبنة القريش في طبق.": "Crumble the qareish cheese onto a plate.",
  "قطعي الخضار مكعبات صغيرة وضيفيها.": "Dice the vegetables small and add them.",
  "رشي النعناع والكمون وقلبي.": "Sprinkle the mint and cumin and mix.",
  "رشي زيت الزيتون وقدميها مع العيش السن.": "Drizzle olive oil and serve with the whole-wheat bread.",
  // b_veg_omelette
  "أومليت خضار مع برتقالة": "Vegetable omelette with an orange",
  "أومليت ٢ بيضة + بياض + برتقالة": "2-egg omelette + 1 egg white + 1 orange",
  "٢ بيضة + ١ بياض": "2 eggs + 1 egg white",
  "حفنة سبانخ أو جرجير": "A handful of spinach or arugula",
  "ربع فلفل رومي": "1/4 bell pepper",
  "١ برتقالة": "1 orange",
  "ملح خفيف وفلفل أسود": "A little salt and black pepper",
  "اخفقي البيض والبياض مع الملح والفلفل.": "Whisk the eggs and white with salt and pepper.",
  "شوحي البصل والفلفل والسبانخ في الزيت دقيقتين.": "Sauté the onion, pepper and spinach in the oil for 2 minutes.",
  "صبي البيض على الخضار في طاسة تيفال.": "Pour the eggs over the vegetables in a non-stick pan.",
  "غطيها على نار هادية لحد ما تستوي وطبقيها.": "Cover over low heat until set, then fold.",
  "قدميها مع البرتقالة.": "Serve with the orange.",
  // b_greek_yogurt_bowl
  "زبادي يوناني بالتوت وبذور الشيا": "Greek yogurt with berries and chia seeds",
  "بولة ٢٥٠ جم": "250 g bowl",
  "٢٠٠ جم زبادي يوناني قليل الدسم": "200 g low-fat Greek yogurt",
  "١٠٠ جم فراولة أو توت": "100 g strawberries or berries",
  "١ معلقة كبيرة بذور شيا": "1 tbsp chia seeds",
  "٧ حبات لوز مقطع": "7 almonds, chopped",
  "حطي الزبادي في بولة.": "Put the yogurt in a bowl.",
  "قطعي الفراولة ورصيها فوقه.": "Slice the strawberries and arrange on top.",
  "رشي بذور الشيا واللوز.": "Sprinkle the chia seeds and almonds.",
  "سيبيها ٥ دقايق في التلاجة لو حابة الشيا تطرى.": "Chill 5 minutes if you want the chia softer.",
  // b_foul_tahini
  "فول بالطحينة والكمون مع خضار": "Ful with tahini, cumin and vegetables",
  "طبق ٢٠٠ جم + خضار": "200 g plate + vegetables",
  "٢٠٠ جم فول مدمس": "200 g ful medames (fava beans)",
  "١ معلقة كبيرة طحينة": "1 tbsp tahini",
  "عصير نص ليمونة": "Juice of 1/2 lemon",
  "فص توم مهروس": "1 garlic clove, crushed",
  "كمون وملح خفيف": "Cumin and a little salt",
  "خيار وفلفل وجرجير": "Cucumber, pepper and arugula",
  "سخني الفول واهرسيه نص هرسة.": "Warm the ful and mash it halfway.",
  "اخلطي الطحينة بالليمون والتوم ومعلقة مية.": "Mix the tahini with lemon, garlic and 1 tbsp water.",
  "صبي خليط الطحينة على الفول.": "Pour the tahini mix over the ful.",
  "رشي الكمون وقدميه مع الخضار بدل العيش.": "Sprinkle cumin and serve with vegetables instead of bread.",
  // b_cheese_egg_wrap
  "رول تورتيلا سن بالبيض والجبنة": "Whole-wheat tortilla wrap with egg and cheese",
  "رول واحد كبير": "1 large wrap",
  "١ رغيف تورتيلا قمح كامل (٦٠ جم)": "1 whole-wheat tortilla (60 g)",
  "٣٠ جم جبنة موتزاريلا لايت": "30 g light mozzarella",
  "خس وطماطم": "Lettuce and tomato",
  "رشة زعتر": "A pinch of za'atar",
  "اخفقي البيض واعمليه سكرامبل في طاسة تيفال من غير زيت.": "Whisk the eggs and scramble in a non-stick pan without oil.",
  "سخني التورتيلا على الطاسة نص دقيقة.": "Warm the tortilla in the pan for 30 seconds.",
  "رصي البيض والجبنة والخضار في النص.": "Arrange the egg, cheese and vegetables in the middle.",
  "لفيها رول وسخنيها دقيقة لحد ما الجبنة تسيح.": "Roll it up and heat 1 minute until the cheese melts.",
  // b_sweet_potato_egg
  "بطاطا مشوية مع بيض مسلوق": "Roasted sweet potato with boiled eggs",
  "١٥٠ جم بطاطا + ٢ بيضة": "150 g sweet potato + 2 eggs",
  "١٥٠ جم بطاطا": "150 g sweet potato",
  "رشة قرفة أو فلفل أسود": "A pinch of cinnamon or black pepper",
  "اغسلي البطاطا ولفيها في ورق قصدير.": "Wash the sweet potato and wrap it in foil.",
  "اشويها في الفرن ٣٠ دقيقة على ٢٠٠ درجة (أو اسلقيها).": "Roast 30 minutes at 200°C (or boil it).",
  "اسلقي البيض ٩ دقايق.": "Boil the eggs 9 minutes.",
  "قدمي البطاطا مع البيض والخيار.": "Serve the sweet potato with the eggs and cucumber.",
  // b_labneh_zaatar
  "لبنة بالزعتر وزيت الزيتون مع عيش سن": "Labneh with za'atar and olive oil, with whole-wheat bread",
  "٧٥ جم لبنة + نص رغيف سن": "75 g labneh + 1/2 whole-wheat loaf",
  "٧٥ جم لبنة لايت": "75 g light labneh",
  "١ معلقة صغيرة زعتر": "1 tsp za'atar",
  "٤ زيتونات": "4 olives",
  "خيار وطماطم ونعناع": "Cucumber, tomato and mint",
  "افردي اللبنة في طبق.": "Spread the labneh on a plate.",
  "رشي عليها الزعتر وزيت الزيتون.": "Sprinkle with za'atar and olive oil.",
  "قطعي الخيار والطماطم وحطي الزيتون والنعناع جنبها.": "Slice the cucumber and tomato and add the olives and mint on the side.",
  "قدميها مع نص الرغيف السن.": "Serve with the 1/2 whole-wheat loaf.",
  // b_belila
  "بليلة باللبن والقرفة والمكسرات": "Belila (wheat berries) with milk, cinnamon and nuts",
  "١٥٠ جم قمح بليلة مسلوق": "150 g cooked belila wheat berries",
  "٢٠٠ مل لبن قليل الدسم": "200 ml low-fat milk",
  "١ معلقة صغيرة عسل نحل (اختياري)": "1 tsp honey (optional)",
  "٥ حبات لوز أو بندق مقطع": "5 almonds or hazelnuts, chopped",
  "سخني اللبن مع القرفة.": "Warm the milk with the cinnamon.",
  "ضيفي القمح المسلوق وسيبيه يسخن دقيقتين.": "Add the cooked wheat and heat 2 minutes.",
  "صبيه في بولة وضيفي العسل لو حابة.": "Pour into a bowl and add honey if you like.",
  "رشي المكسرات على الوش.": "Sprinkle the nuts on top.",
  // b_banana_oat_pancake
  "بان كيك الموز والشوفان": "Banana oat pancakes",
  "٣ بان كيك صغيرين": "3 small pancakes",
  "٤٠ جم شوفان مطحون": "40 g ground oats",
  "١ موزة مهروسة": "1 banana, mashed",
  "١ بيضة": "1 egg",
  "٢ معلقة كبيرة لبن": "2 tbsp milk",
  "رشة قرفة ونص معلقة صغيرة بيكنج باودر": "A pinch of cinnamon and 1/2 tsp baking powder",
  "اهرسي الموزة واخلطيها مع البيضة واللبن.": "Mash the banana and mix with the egg and milk.",
  "ضيفي الشوفان المطحون والقرفة والبيكنج باودر.": "Add the ground oats, cinnamon and baking powder.",
  "سخني طاسة تيفال من غير زيت.": "Heat a non-stick pan without oil.",
  "صبي معلقة كبيرة من الخليط لكل بان كيك واقلبيها لما تعمل فقاقيع.": "Pour 1 tbsp batter per pancake and flip when bubbles form.",
  "قدميها مع شرايح فاكهة بدل الشربات.": "Serve with fruit slices instead of syrup.",
  // b_taameya_air
  "طعمية في الإير فراير مع سلطة وطحينة": "Air-fryer ta'ameya (Egyptian falafel) with salad and tahini",
  "٥ أقراص + سلطة": "5 patties + salad",
  "١٢٠ جم خليط طعمية (فول مدشوش مع خضرة)": "120 g ta'ameya mix (crushed fava beans with herbs)",
  "١ معلقة صغيرة زيت للرش": "1 tsp oil for spraying",
  "١ معلقة كبيرة طحينة بالليمون": "1 tbsp tahini with lemon",
  "سلطة خضرا (خيار وطماطم وخس)": "Green salad (cucumber, tomato, lettuce)",
  "شكلي الخليط ٥ أقراص صغيرة.": "Shape the mix into 5 small patties.",
  "ارشي عليهم زيت خفيف بالبخاخة.": "Spray lightly with oil.",
  "اشويهم في الإير فراير ١٢ دقيقة على ١٨٠ درجة مع التقليب في النص.": "Air-fry 12 minutes at 180°C, flipping halfway.",
  "قدميهم مع السلطة والطحينة من غير عيش.": "Serve with the salad and tahini, no bread.",
  // l_chicken_lemon_garlic
  "فراخ مشوية بالليمون والثوم مع خضار": "Roast lemon-garlic chicken with vegetables",
  "١٨٠ جم صدور + خضار + بطاطس": "180 g chicken breast + vegetables + potatoes",
  "١٨٠ جم صدور فراخ": "180 g chicken breast",
  "عصير ليمونة": "Juice of 1 lemon",
  "٣ فصوص توم مهروسة": "3 garlic cloves, crushed",
  "١٥٠ جم بطاطس مقطعة": "150 g potatoes, cut",
  "كوسة وجزر وفلفل": "Zucchini, carrot and pepper",
  "زعتر وبابريكا وملح خفيف": "Thyme, paprika and a little salt",
  "تبلي الفراخ بالليمون والتوم والزيت والتوابل ٢٠ دقيقة على الأقل.": "Marinate the chicken in lemon, garlic, oil and spices for at least 20 minutes.",
  "رصي البطاطس والخضار في صينية حواليها.": "Arrange the potatoes and vegetables around it in a tray.",
  "اشويها في الفرن ٢٥-٣٠ دقيقة على ٢٠٠ درجة.": "Roast 25-30 minutes at 200°C.",
  "شغلي الشواية من فوق آخر ٥ دقايق عشان تتحمر.": "Turn on the top grill for the last 5 minutes to brown.",
  // l_tilapia_grilled
  "سمك بلطي مشوي مع رز بني وسلطة": "Grilled tilapia with brown rice and salad",
  "سمكة متوسطة + ١٥٠ جم رز بني": "1 medium fish + 150 g brown rice",
  "١ سمكة بلطي متوسطة (٣٠٠ جم بالعضم)": "1 medium tilapia (300 g bone-in)",
  "كمون وتوم وليمون وملح خفيف": "Cumin, garlic, lemon and a little salt",
  "١ معلقة صغيرة زيت": "1 tsp oil",
  "١٥٠ جم رز بني مطبوخ": "150 g cooked brown rice",
  "سلطة خضرا كبيرة": "Large green salad",
  "اعملي شقوق في السمكة وتبليها بالكمون والتوم والليمون.": "Score the fish and season with cumin, garlic and lemon.",
  "ادهني الصينية بالزيت وحطي السمكة.": "Oil the tray and lay the fish on it.",
  "اشويها في الفرن ٢٠-٢٥ دقيقة على ٢٢٠ درجة.": "Bake 20-25 minutes at 220°C.",
  "قدميها مع الرز البني والسلطة.": "Serve with the brown rice and salad.",
  // l_salmon_oven
  "سلمون في الفرن مع بطاطا وبروكلي": "Baked salmon with sweet potato and broccoli",
  "١٥٠ جم سلمون + خضار": "150 g salmon + vegetables",
  "١٥٠ جم فيليه سلمون": "150 g salmon fillet",
  "١٥٠ جم بطاطا مسلوقة": "150 g boiled sweet potato",
  "١٠٠ جم بروكلي": "100 g broccoli",
  "شبت وتوم وفلفل أسود": "Dill, garlic and black pepper",
  "تبلي السلمون بالليمون والتوم والشبت.": "Season the salmon with lemon, garlic and dill.",
  "حطيه في صينية مع البروكلي.": "Put it in a tray with the broccoli.",
  "ادخليه الفرن ١٥-١٨ دقيقة على ٢٠٠ درجة.": "Bake 15-18 minutes at 200°C.",
  "قدميه مع البطاطا المسلوقة.": "Serve with the boiled sweet potato.",
  // l_potato_chicken_tray
  "صينية بطاطس بالفراخ في الفرن": "Oven tray of potatoes and chicken (Sineyet batates)",
  "طبق ٤٠٠ جم": "400 g plate",
  "١٥٠ جم صدور أو أوراك فراخ من غير جلد": "150 g skinless chicken breast or thighs",
  "٢٠٠ جم بطاطس شرايح": "200 g potatoes, sliced",
  "نص بصلة": "1/2 onion",
  "نص فلفل رومي": "1/2 bell pepper",
  "١ معلقة كبيرة صلصة": "1 tbsp tomato paste",
  "بهارات وملح خفيف": "Spices and a little salt",
  "رصي البطاطس والبصل والفلفل في صينية.": "Arrange the potatoes, onion and pepper in a tray.",
  "حطي الفراخ المتبلة فوقهم.": "Lay the seasoned chicken on top.",
  "اخلطي الصلصة بكوباية مية والتوابل وصبيها على الصينية.": "Mix the tomato paste with 1 cup water and the spices and pour over the tray.",
  "غطيها بالقصدير ٣٠ دقيقة على ٢٠٠ درجة.": "Cover with foil and bake 30 minutes at 200°C.",
  "شيلي القصدير وسيبيها ١٥ دقيقة لحد ما تتحمر.": "Remove the foil and bake 15 minutes until browned.",
  // l_molokhia_chicken
  "ملوخية بصدور فراخ ورز بني": "Molokhia (jute leaf stew) with chicken breast and brown rice",
  "طبق ملوخية + ١٥٠ جم فراخ + رز": "Molokhia plate + 150 g chicken + rice",
  "١٥٠ جم صدور فراخ": "150 g chicken breast",
  "٢٠٠ جم ملوخية مفرومة": "200 g minced molokhia (jute leaves)",
  "٣٠٠ مل شوربة فراخ": "300 ml chicken broth",
  "٣ فصوص توم": "3 garlic cloves",
  "كزبرة ناشفة": "Dried coriander",
  "١ معلقة صغيرة سمنة أو زيت": "1 tsp ghee or oil",
  "١٢٠ جم رز بني مطبوخ": "120 g cooked brown rice",
  "اسلقي الفراخ مع بصلة وورق لورا وخدي الشوربة.": "Boil the chicken with an onion and bay leaf and keep the broth.",
  "غلي الشوربة وضيفي الملوخية وقلبي من غير ما تغطيها.": "Bring the broth to a boil, add the molokhia and stir without covering.",
  "شوحي التوم والكزبرة في المعلقة الصغيرة وضيفيها (الطشة).": "Fry the garlic and coriander in the teaspoon of fat and add it (the \"tasha\").",
  "اشوي الفراخ المسلوقة في الفرن ١٠ دقايق.": "Roast the boiled chicken in the oven for 10 minutes.",
  "قدميها مع الرز البني.": "Serve with the brown rice.",
  // l_brown_rice_veg
  "رز بني بالخضار مع زبادي": "Brown rice with vegetables and yogurt",
  "طبق ٣٥٠ جم + زبادي": "350 g plate + yogurt",
  "٧٠ جم رز بني ني": "70 g raw brown rice",
  "جزر وبسلة وذرة وفاصوليا (١٥٠ جم)": "Carrot, peas, corn and green beans (150 g)",
  "ربع بصلة": "1/4 onion",
  "١٧٠ جم زبادي": "170 g yogurt",
  "كركم وكمون وملح خفيف": "Turmeric, cumin and a little salt",
  "انقعي الرز البني نص ساعة واغسليه.": "Soak the brown rice 30 minutes and rinse.",
  "شوحي البصل في الزيت وضيفي الخضار.": "Sauté the onion in the oil and add the vegetables.",
  "ضيفي الرز والتوابل ومية (ضعف كمية الرز ونص).": "Add the rice, spices and water (2.5 times the rice).",
  "غطيه على نار هادية ٣٥ دقيقة لحد ما يستوي.": "Cover over low heat 35 minutes until cooked.",
  "قدميه مع الزبادي.": "Serve with the yogurt.",
  // l_whole_pasta_chicken
  "مكرونة سن بصوص الطماطم والفراخ": "Whole-wheat pasta with tomato sauce and chicken",
  "٨٠ جم مكرونة قمح كامل (ني)": "80 g whole-wheat pasta (dry)",
  "١٢٠ جم صدور فراخ مكعبات": "120 g chicken breast, cubed",
  "٢ فص توم": "2 garlic cloves",
  "ريحان وأوريجانو وفلفل أسود": "Basil, oregano and black pepper",
  "اسلقي المكرونة في مية بملح خفيف ٨-١٠ دقايق وصفيها.": "Boil the pasta in lightly salted water 8-10 minutes and drain.",
  "شوحي الفراخ في الزيت لحد ما تبيض.": "Sauté the chicken in the oil until it turns white.",
  "ضيفي التوم والطماطم والتوابل وسيبيها ١٠ دقايق.": "Add the garlic, tomatoes and spices and cook 10 minutes.",
  "قلبي المكرونة في الصوص وقدميها.": "Toss the pasta in the sauce and serve.",
  // l_kofta_meat
  "كفتة لحمة مشوية مع سلطة وطحينة": "Grilled beef kofta with salad and tahini",
  "١٥٠ جم كفتة + سلطة + نص رغيف سن": "150 g kofta + salad + 1/2 whole-wheat loaf",
  "١٥٠ جم لحمة مفرومة قليلة الدهن": "150 g lean minced beef",
  "ربع بصلة مبشورة ومصفية": "1/4 onion, grated and drained",
  "بقدونس مفروم": "Chopped parsley",
  "بهارات كفتة وملح خفيف": "Kofta spices and a little salt",
  "سلطة بلدي": "Baladi salad (Egyptian chopped salad)",
  "اعجني اللحمة مع البصل والبقدونس والبهارات.": "Knead the meat with the onion, parsley and spices.",
  "شكليها أصابع على أسياخ أو من غير.": "Shape into fingers, on skewers or not.",
  "اشويها في الفرن أو على الجريل ١٥ دقيقة مع التقليب.": "Grill or bake 15 minutes, turning.",
  "قدميها مع السلطة والطحينة ونص الرغيف.": "Serve with the salad, tahini and 1/2 loaf.",
  // l_shish_tawook
  "شيش طاووق مع رز بني وصوص زبادي": "Shish tawook with brown rice and yogurt sauce",
  "١٨٠ جم فراخ + ١٢٠ جم رز": "180 g chicken + 120 g rice",
  "١٨٠ جم صدور فراخ مكعبات": "180 g chicken breast, cubed",
  "٣ معالق زبادي": "3 tbsp yogurt",
  "١ معلقة صغيرة صلصة": "1 tsp tomato paste",
  "توم وليمون وبابريكا": "Garlic, lemon and paprika",
  "فلفل ألوان وبصل": "Colored peppers and onion",
  "تبلي الفراخ بالزبادي والصلصة والتوم والليمون والزيت ساعة.": "Marinate the chicken in yogurt, tomato paste, garlic, lemon and oil for 1 hour.",
  "شكيها في أسياخ مع الفلفل والبصل.": "Thread onto skewers with the peppers and onion.",
  "اشويها في الفرن ٢٠ دقيقة على ٢٢٠ درجة مع التقليب.": "Bake 20 minutes at 220°C, turning.",
  "قدميها مع الرز البني وصوص زبادي بالتوم.": "Serve with brown rice and garlic yogurt sauce.",
  // l_mahshi_zucchini
  "محشي كوسة في الفرن بالرز البني": "Oven-baked mahshi kousa (stuffed zucchini) with brown rice",
  "٦ صوابع كوسة + زبادي": "6 stuffed zucchini + yogurt",
  "٦ كوسايات صغيرة (٤٠٠ جم)": "6 small zucchini (400 g)",
  "٦٠ جم رز بني ني": "60 g raw brown rice",
  "شبت وبقدونس وكزبرة مفرومين": "Chopped dill, parsley and coriander",
  "قوري الكوسة.": "Core the zucchini.",
  "اخلطي الرز (منقوع ساعة) مع الطماطم والخضرة والزيت والبهارات.": "Mix the rice (soaked 1 hour) with tomato, herbs, oil and spices.",
  "احشي الكوسة لتلاتة أرباعها.": "Stuff the zucchini three-quarters full.",
  "رصيها في صينية وغطيها بمرقة طماطم.": "Arrange in a tray and cover with tomato broth.",
  "غطيها بالقصدير واخبزيها ٥٠ دقيقة على ٢٠٠ درجة.": "Cover with foil and bake 50 minutes at 200°C.",
  "قدميها مع الزبادي.": "Serve with the yogurt.",
  // l_kebab_hala
  "كباب حلة مع رز بني": "Kebab halla (braised beef and onions) with brown rice",
  "١٥٠ جم لحمة + ١٢٠ جم رز": "150 g meat + 120 g rice",
  "١٥٠ جم لحمة كندوز مكعبات من غير دهن": "150 g lean beef chuck, cubed, fat removed",
  "٢ بصلة متوسطة شرايح": "2 medium onions, sliced",
  "حبهان وورق لورا وفلفل أسود": "Cardamom, bay leaf and black pepper",
  "ملح خفيف": "A little salt",
  "شوحي اللحمة في الزيت لحد ما تتقفل من كل ناحية.": "Sear the meat in the oil on all sides.",
  "ضيفي البصل وقلبي لحد ما يدبل.": "Add the onions and stir until soft.",
  "ضيفي التوابل ومية تغطيها.": "Add the spices and water to cover.",
  "سيبيها على نار هادية ساعة لحد ما تستوي والبصل يبقى صوص.": "Simmer on low heat 1 hour until tender and the onions turn into a sauce.",
  "قدميها مع الرز البني وسلطة.": "Serve with brown rice and salad.",
  // l_koshary_healthy
  "كشري صحي بالرز البني والمكرونة السن": "Healthy koshary with brown rice and whole-wheat pasta",
  "٤٠ جم عدس بجبة ني": "40 g raw brown lentils",
  "٤٠ جم رز بني ني": "40 g raw brown rice",
  "٣٠ جم مكرونة سن ني": "30 g raw whole-wheat pasta",
  "٣٠ جم حمص مسلوق": "30 g cooked chickpeas",
  "نص بصلة شرايح محمرة في الفرن": "1/2 onion, sliced and oven-browned",
  "صلصة طماطم بالتوم والخل": "Tomato sauce with garlic and vinegar",
  "اسلقي العدس لحد ما ينضج نص سوا.": "Boil the lentils until half cooked.",
  "ضيفي الرز والمية وكملي لحد ما يستوي.": "Add the rice and water and cook until done.",
  "اسلقي المكرونة لوحدها.": "Boil the pasta separately.",
  "حمري البصل في الفرن بمعلقة الزيت بدل القلي.": "Brown the onion in the oven with the spoon of oil instead of frying.",
  "اعملي الصلصة بالطماطم والتوم والخل والكمون.": "Make the sauce with tomato, garlic, vinegar and cumin.",
  "جمعي الطبق وحطي الحمص والبصل على الوش.": "Assemble the plate and top with the chickpeas and onion.",
  // l_okra_chicken
  "طاجن بامية بصدور الفراخ مع رز بني": "Okra tagine with chicken breast and brown rice",
  "طاجن ٣٠٠ جم + ١٢٠ جم رز": "300 g tagine + 120 g rice",
  "٢٠٠ جم بامية": "200 g okra",
  "١٣٠ جم صدور فراخ مكعبات": "130 g chicken breast, cubed",
  "ربع بصلة و٢ فص توم": "1/4 onion and 2 garlic cloves",
  "كزبرة ناشفة وملح خفيف": "Dried coriander and a little salt",
  "شوحي البصل والتوم والفراخ في الزيت.": "Sauté the onion, garlic and chicken in the oil.",
  "ضيفي الطماطم والبامية والكزبرة.": "Add the tomatoes, okra and coriander.",
  "حطيهم في طاجن وضيفي شوية مية.": "Put in a tagine dish and add a little water.",
  "ادخليه الفرن ٤٠ دقيقة على ٢٠٠ درجة.": "Bake 40 minutes at 200°C.",
  "قدميه مع الرز البني.": "Serve with the brown rice.",
  // l_white_beans
  "فاصوليا بيضا بالصلصة مع رز بني": "White beans in tomato sauce with brown rice",
  "طبق ٢٥٠ جم + ١٢٠ جم رز": "250 g plate + 120 g rice",
  "٦٠ جم فاصوليا بيضا ناشفة (منقوعة ليلة)": "60 g dried white beans (soaked overnight)",
  "اسلقي الفاصوليا المنقوعة لحد ما تستوي (أو في الحلة البريستو ٢٠ دقيقة).": "Boil the soaked beans until tender (or 20 minutes in a pressure cooker).",
  "شوحي البصل في الزيت وضيفي الطماطم والصلصة.": "Sauté the onion in the oil and add the tomatoes and tomato paste.",
  "ضيفي الفاصوليا والتوابل ومية وسيبيها تتسبك ١٥ دقيقة.": "Add the beans, spices and water and simmer 15 minutes.",
  // l_sardine_oven
  "سردين في الفرن بالطماطم مع رز بني": "Oven-baked sardines with tomato and brown rice",
  "١٥٠ جم سردين + ١٢٠ جم رز": "150 g sardines + 120 g rice",
  "١٥٠ جم سردين طازة منضف": "150 g fresh sardines, cleaned",
  "شرايح طماطم وفلفل": "Tomato and pepper slices",
  "كمون وتوم وليمون": "Cumin, garlic and lemon",
  "سلطة خضرا": "Green salad",
  "نضفي السردين وتبليه بالكمون والتوم والليمون.": "Clean the sardines and season with cumin, garlic and lemon.",
  "رصيه في صينية مدهونة بالزيت مع الطماطم والفلفل.": "Arrange in an oiled tray with the tomato and pepper.",
  "اشويه في الفرن ٢٠ دقيقة على ٢٢٠ درجة.": "Bake 20 minutes at 220°C.",
  "قدميه مع الرز البني والسلطة.": "Serve with the brown rice and salad.",
  // l_freekeh_chicken
  "فريك بالفراخ": "Freekeh (green cracked wheat) with chicken",
  "١٥٠ جم فراخ + ١٥٠ جم فريك مطبوخ": "150 g chicken + 150 g cooked freekeh",
  "٦٠ جم فريك ني": "60 g raw freekeh",
  "٢٥٠ مل شوربة فراخ": "250 ml chicken broth",
  "حبهان وفلفل أسود وملح خفيف": "Cardamom, black pepper and a little salt",
  "اسلقي الفراخ مع البصل والحبهان وخدي الشوربة.": "Boil the chicken with onion and cardamom and keep the broth.",
  "اغسلي الفريك وشوحيه في المعلقة الصغيرة.": "Rinse the freekeh and sauté it in the teaspoon of fat.",
  "ضيفي الشوربة وسيبيه على نار هادية ٣٠ دقيقة.": "Add the broth and cook on low heat 30 minutes.",
  "حمري الفراخ في الفرن وقدميها فوق الفريك.": "Brown the chicken in the oven and serve over the freekeh.",
  // d_lentil_soup
  "شوربة عدس أصفر بالخضار": "Yellow lentil soup with vegetables",
  "سلطانية ٣٥٠ مل": "350 ml bowl",
  "٦٠ جم عدس أصفر": "60 g yellow lentils",
  "١ جزرة": "1 carrot",
  "ليمون للتقديم": "Lemon for serving",
  "اغسلي العدس وحطيه مع الخضار المقطعة في حلة.": "Rinse the lentils and put them in a pot with the chopped vegetables.",
  "غطيهم بمية وسيبيهم يغلوا ٢٥ دقيقة.": "Cover with water and boil 25 minutes.",
  "اضربيهم في الخلاط.": "Blend until smooth.",
  "ضيفي الكمون والزيت وسخنيها دقيقتين.": "Add the cumin and oil and heat 2 minutes.",
  "قدميها بالليمون.": "Serve with lemon.",
  // d_tuna_salad
  "سلطة تونة بالخضار": "Tuna salad with vegetables",
  "طبق ٣٠٠ جم": "300 g plate",
  "١ علبة تونة في مية (١٢٠ جم مصفية)": "1 can tuna in water (120 g drained)",
  "خس وخيار وطماطم": "Lettuce, cucumber and tomato",
  "٢ معلقة كبيرة ذرة": "2 tbsp corn",
  "ليمون وخل وكمون": "Lemon, vinegar and cumin",
  "صفي التونة كويس من المية.": "Drain the tuna well.",
  "قطعي الخضار في بولة كبيرة.": "Chop the vegetables into a large bowl.",
  "ضيفي التونة والذرة.": "Add the tuna and corn.",
  "اخلطي الزيت والليمون والخل والكمون وصبيهم على السلطة.": "Mix the oil, lemon, vinegar and cumin and pour over the salad.",
  // d_chicken_kofta_sandwich
  "ساندوتش كفتة فراخ في الفرن": "Oven-baked chicken kofta sandwich",
  "رغيف بلدي سن + ١٢٠ جم كفتة": "Whole-wheat baladi loaf + 120 g kofta",
  "١٢٠ جم صدور فراخ مفرومة": "120 g minced chicken breast",
  "ربع بصلة مبشورة": "1/4 onion, grated",
  "بقدونس وتوم": "Parsley and garlic",
  "١ رغيف بلدي سن صغير": "1 small whole-wheat baladi loaf",
  "خس وطماطم ومعلقة طحينة": "Lettuce, tomato and 1 tbsp tahini",
  "اعجني الفراخ المفرومة مع البصل والبقدونس والبهارات.": "Knead the minced chicken with the onion, parsley and spices.",
  "شكليها أصابع ورصيها في صينية بورق زبدة.": "Shape into fingers and arrange on a parchment-lined tray.",
  "اشويها ١٥-٢٠ دقيقة على ٢٠٠ درجة.": "Bake 15-20 minutes at 200°C.",
  "احشي الرغيف بالكفتة والخضار والطحينة.": "Fill the bread with the kofta, vegetables and tahini.",
  // d_oven_kebab
  "كباب لحمة في الفرن بالخضار": "Oven-baked beef kebab with vegetables",
  "١٢٠ جم لحمة + خضار": "120 g meat + vegetables",
  "١٢٠ جم لحمة مكعبات قليلة الدهن": "120 g lean beef, cubed",
  "بصلة وطماطم وفلفل مكعبات": "Onion, tomato and pepper, cubed",
  "زبادي وخل وتوم للتتبيلة": "Yogurt, vinegar and garlic for the marinade",
  "بهارات كباب وملح خفيف": "Kebab spices and a little salt",
  "تبلي اللحمة بالزبادي والخل والتوم والبهارات ساعتين.": "Marinate the meat in yogurt, vinegar, garlic and spices for 2 hours.",
  "شكيها في أسياخ مع الخضار.": "Thread onto skewers with the vegetables.",
  "اشويها في الفرن ٢٠-٢٥ دقيقة على أعلى حرارة مع التقليب.": "Bake 20-25 minutes at the highest heat, turning.",
  "قدميها مع سلطة خضرا.": "Serve with a green salad.",
  // d_grilled_chicken_salad
  "سلطة فراخ مشوية": "Grilled chicken salad",
  "طبق ٣٥٠ جم": "350 g plate",
  "١٢٠ جم صدور فراخ": "120 g chicken breast",
  "خس وجرجير وخيار وطماطم": "Lettuce, arugula, cucumber and tomato",
  "ربع كوب ذرة أو فول صويا": "1/4 cup corn or soybeans",
  "ليمون ومستردة وتوم": "Lemon, mustard and garlic",
  "تبلي الفراخ بالليمون والتوم والبهارات.": "Season the chicken with lemon, garlic and spices.",
  "اشويها في جريل أو طاسة تيفال ٦ دقايق لكل ناحية.": "Grill or cook in a non-stick pan 6 minutes per side.",
  "قطعيها شرايح.": "Slice it.",
  "رصيها على الخضار وصبي صوص الليمون والمستردة.": "Lay it on the greens and pour over the lemon-mustard dressing.",
  // d_mackerel_grilled
  "ماكريل مشوي مع سلطة": "Grilled mackerel with salad",
  "١٢٠ جم سمك + سلطة": "120 g fish + salad",
  "١٢٠ جم سمك ماكريل طازة": "120 g fresh mackerel",
  "سلطة طحينة خفيفة أو سلطة خضرا": "Light tahini salad or green salad",
  "نضفي السمك وتبليه بالكمون والتوم والليمون.": "Clean the fish and season with cumin, garlic and lemon.",
  "اشويه في الفرن ١٥-٢٠ دقيقة على ٢٢٠ درجة.": "Bake 15-20 minutes at 220°C.",
  "قدميه مع السلطة.": "Serve with the salad.",
  // d_veg_chicken_soup
  "شوربة خضار بالفراخ": "Chicken and vegetable soup",
  "سلطانية ٤٠٠ مل": "400 ml bowl",
  "١٠٠ جم صدور فراخ مكعبات": "100 g chicken breast, cubed",
  "جزر وكوسة وبسلة وكرفس (٣٠٠ جم)": "Carrot, zucchini, peas and celery (300 g)",
  "شوحي البصل والفراخ في الزيت.": "Sauté the onion and chicken in the oil.",
  "ضيفي الخضار والطماطم.": "Add the vegetables and tomato.",
  "غطيهم بمية أو شوربة وسيبيهم ٢٥ دقيقة.": "Cover with water or broth and cook 25 minutes.",
  "تبليها وقدميها سخنة.": "Season and serve hot.",
  // d_hummus_plate
  "حمص بالطحينة مع خضار وعيش سن": "Hummus with tahini, vegetables and whole-wheat bread",
  "١٢٠ جم حمص + نص رغيف سن": "120 g hummus + 1/2 whole-wheat loaf",
  "١٠٠ جم حمص مسلوق": "100 g cooked chickpeas",
  "عصير ليمونة وفص توم": "Juice of 1 lemon and 1 garlic clove",
  "رشة كمون": "A pinch of cumin",
  "جزر وخيار وفلفل أصابع": "Carrot, cucumber and pepper sticks",
  "اضربي الحمص مع الطحينة والليمون والتوم في الخلاط.": "Blend the chickpeas with the tahini, lemon and garlic.",
  "ضيفي شوية مية تلج لحد ما يبقى ناعم.": "Add a little ice water until smooth.",
  "قطعي الخضار أصابع.": "Cut the vegetables into sticks.",
  "قدميه مع الخضار ونص الرغيف.": "Serve with the vegetables and 1/2 loaf.",
  // d_mushroom_omelette
  "أومليت مشروم وسبانخ بالجبنة القريش": "Mushroom and spinach omelette with qareish cheese",
  "أومليت ٢ بيضة": "2-egg omelette",
  "٥٠ جم جبنة قريش": "50 g qareish cheese",
  "٨٠ جم مشروم شرايح": "80 g mushrooms, sliced",
  "حفنة سبانخ": "A handful of spinach",
  "فلفل أسود وملح خفيف": "Black pepper and a little salt",
  "شوحي المشروم في الزيت لحد ما مايته تنشف.": "Sauté the mushrooms in the oil until their liquid evaporates.",
  "ضيفي السبانخ لحد ما تدبل.": "Add the spinach until wilted.",
  "صبي البيض المخفوق ورشي القريش.": "Pour in the beaten eggs and sprinkle the qareish.",
  "غطيها على نار هادية لحد ما تستوي.": "Cover over low heat until set.",
  // d_shrimp_grilled
  "جمبري مشوي مع رز بني": "Grilled shrimp with brown rice",
  "١٥٠ جم جمبري + ١٠٠ جم رز": "150 g shrimp + 100 g rice",
  "١٥٠ جم جمبري منضف": "150 g cleaned shrimp",
  "١٠٠ جم رز بني مطبوخ": "100 g cooked brown rice",
  "تبلي الجمبري بالتوم والليمون والبابريكا والزيت.": "Season the shrimp with garlic, lemon, paprika and oil.",
  "اشويه في طاسة جريل ٢-٣ دقايق لكل ناحية.": "Cook in a grill pan 2-3 minutes per side.",
  // d_baked_eggplant
  "مسقعة خفيفة في الفرن بالجبنة": "Light oven-baked mesa'a'a (eggplant moussaka) with cheese",
  "١ بتنجانة متوسطة (٣٠٠ جم) شرايح": "1 medium eggplant (300 g), sliced",
  "خل وكمون وملح خفيف": "Vinegar, cumin and a little salt",
  "رشي شرايح البتنجان بالزيت واشويها في الفرن ٢٠ دقيقة بدل القلي.": "Brush the eggplant slices with oil and bake 20 minutes instead of frying.",
  "اعملي صوص طماطم بالتوم والفلفل والخل.": "Make a tomato sauce with garlic, pepper and vinegar.",
  "رصي البتنجان في طاجن وصبي عليه الصوص.": "Arrange the eggplant in a baking dish and pour the sauce over.",
  "رشي الجبنة وادخليه الفرن ١٥ دقيقة.": "Sprinkle the cheese and bake 15 minutes.",
  // d_chicken_shawarma_bowl
  "بول شاورما فراخ في الفرن بالطحينة": "Oven chicken shawarma bowl with tahini",
  "١٢٠ جم فراخ + سلطة": "120 g chicken + salad",
  "١٢٠ جم صدور فراخ شرايح رفيعة": "120 g chicken breast, thinly sliced",
  "بهارات شاورما وخل وتوم وزبادي للتتبيلة": "Shawarma spices, vinegar, garlic and yogurt for the marinade",
  "خس وطماطم وخيار مخلل قليل": "Lettuce, tomato and a few pickled cucumbers",
  "تبلي الفراخ بالبهارات والخل والتوم والزبادي ساعة.": "Marinate the chicken in the spices, vinegar, garlic and yogurt for 1 hour.",
  "افرديها في صينية واشويها ٢٠ دقيقة على ٢٢٠ درجة.": "Spread on a tray and bake 20 minutes at 220°C.",
  "رصي السلطة في بولة والفراخ فوقها.": "Put the salad in a bowl and the chicken on top.",
  "صبي الطحينة وقدميها من غير عيش.": "Pour over the tahini and serve without bread.",
  // d_bisara
  "بصارة بالخضرة مع عيش سن": "Bissara (fava bean and herb purée) with whole-wheat bread",
  "طبق ٢٠٠ جم + نص رغيف سن": "200 g plate + 1/2 whole-wheat loaf",
  "٥٠ جم فول مدشوش ني": "50 g raw split fava beans",
  "ملوخية ناشفة وشبت وكزبرة وبقدونس": "Dried molokhia, dill, coriander and parsley",
  "ربع بصلة شرايح محمرة في الفرن": "1/4 onion, sliced and oven-browned",
  "كمون وشطة وملح خفيف": "Cumin, chili and a little salt",
  "اسلقي الفول المدشوش مع التوم لحد ما يستوي.": "Boil the split fava beans with the garlic until cooked.",
  "ضيفي الخضرة واضربيهم في الخلاط.": "Add the herbs and blend.",
  "سخنيها وتبليها بالكمون والشطة.": "Reheat and season with cumin and chili.",
  "زينيها بالبصل المحمر في الفرن وقدميها مع نص الرغيف.": "Top with the oven-browned onion and serve with 1/2 loaf.",
  // d_tilapia_fillet_veg
  "فيليه بلطي في الفرن بالخضار": "Oven-baked tilapia fillet with vegetables",
  "١٥٠ جم سمك + خضار": "150 g fish + vegetables",
  "١٥٠ جم فيليه بلطي": "150 g tilapia fillet",
  "كوسة وجزر وفلفل شرايح": "Zucchini, carrot and pepper, sliced",
  "ليمون وكمون وتوم وملح خفيف": "Lemon, cumin, garlic and a little salt",
  "تبلي الفيليه بالليمون والكمون والتوم.": "Season the fillet with lemon, cumin and garlic.",
  "رصي الخضار في صينية وحطي السمك فوقها.": "Arrange the vegetables in a tray and lay the fish on top.",
  "رشي الزيت وغطيها بالقصدير.": "Drizzle the oil and cover with foil.",
  "اخبزيها ٢٠ دقيقة على ٢٠٠ درجة.": "Bake 20 minutes at 200°C.",
  // s_popcorn
  "فشار في البيت": "Homemade popcorn",
  "٣ كوبايات فشار": "3 cups popcorn",
  "٢٥ جم درة فشار": "25 g popcorn kernels",
  "رشة ملح خفيف أو بابريكا": "A pinch of salt or paprika",
  "سخني الزيت في حلة.": "Heat the oil in a pot.",
  "ضيفي الدرة وغطيها.": "Add the kernels and cover.",
  "هزي الحلة لحد ما الفرقعة تهدى.": "Shake the pot until the popping slows.",
  "رشي الملح أو البابريكا.": "Sprinkle the salt or paprika.",
  // s_roasted_chickpeas
  "حمص مقرمش في الفرن": "Crunchy oven-roasted chickpeas",
  "كوباية صغيرة": "1 small cup",
  "٤٠ جم حمص ناشف (أو ١٠٠ جم مسلوق)": "40 g dried chickpeas (or 100 g cooked)",
  "كمون وبابريكا وملح خفيف": "Cumin, paprika and a little salt",
  "اسلقي الحمص ونشفيه كويس بفوطة.": "Boil the chickpeas and pat dry well with a towel.",
  "قلبيه مع الزيت والتوابل.": "Toss with the oil and spices.",
  "افرديه في صينية واخبزيه ٣٠ دقيقة على ٢٠٠ درجة مع التقليب.": "Spread on a tray and bake 30 minutes at 200°C, stirring.",
  "سيبيه يبرد عشان يقرمش.": "Let cool so they crisp up.",
  // s_termis
  "ترمس بالليمون والكمون": "Termis (lupini beans) with lemon and cumin",
  "١٠٠ جم": "100 g",
  "١٠٠ جم ترمس محلي": "100 g ready-to-eat lupini beans",
  "رشة كمون وشطة": "A pinch of cumin and chili",
  "اغسلي الترمس بمية كتير عشان يخف الملح.": "Rinse the lupini in plenty of water to reduce the salt.",
  "رشي عليه الليمون والكمون والشطة.": "Sprinkle with lemon, cumin and chili.",
  "كليه بالتقشير.": "Peel as you eat.",
  // s_dates_almonds
  "تمر محشي لوز": "Almond-stuffed dates",
  "٣ تمرات + ١٠ لوزات": "3 dates + 10 almonds",
  "٣ تمرات": "3 dates",
  "١٠ لوزات ني": "10 raw almonds",
  "شقي التمر وشيلي النواية.": "Slit the dates and remove the pits.",
  "احشي كل تمرة بلوزة أو اتنين.": "Stuff each date with 1 or 2 almonds.",
  "كلي الباقي جنبهم.": "Eat the rest alongside.",
  // s_sweet_potato_chips
  "شيبس بطاطا في الفرن": "Oven-baked sweet potato chips",
  "بابريكا وملح خفيف": "Paprika and a little salt",
  "قطعي البطاطا شرايح رفيعة جدا.": "Slice the sweet potato very thin.",
  "قلبيها مع الزيت والتوابل.": "Toss with the oil and spices.",
  "افرديها على ورق زبدة من غير ما تركب على بعض.": "Spread on parchment without overlapping.",
  "اخبزيها ٢٠-٢٥ دقيقة على ١٩٠ درجة مع التقليب.": "Bake 20-25 minutes at 190°C, flipping.",
  // s_zucchini_chips
  "شيبس كوسة بالبارميزان في الفرن": "Oven-baked parmesan zucchini chips",
  "كوسايتين": "2 zucchini",
  "٢ كوسة متوسطة (٢٥٠ جم)": "2 medium zucchini (250 g)",
  "١ معلقة كبيرة جبنة بارميزان مبشورة": "1 tbsp grated parmesan",
  "أوريجانو وفلفل أسود": "Oregano and black pepper",
  "قطعي الكوسة شرايح رفيعة ونشفيها.": "Slice the zucchini thin and pat dry.",
  "افرديها في صينية ورشي البارميزان.": "Spread on a tray and sprinkle with parmesan.",
  "اخبزيها ٢٥ دقيقة على ٢٠٠ درجة لحد ما تقرمش.": "Bake 25 minutes at 200°C until crisp.",
  // s_yogurt_fruit
  "زبادي يوناني بالفاكهة": "Greek yogurt with fruit",
  "١٥٠ جم زبادي + فاكهة": "150 g yogurt + fruit",
  "١٥٠ جم زبادي يوناني قليل الدسم": "150 g low-fat Greek yogurt",
  "١٠٠ جم فراولة أو كيوي أو تفاح": "100 g strawberries, kiwi or apple",
  "حطي الزبادي في كوباية.": "Put the yogurt in a glass.",
  "قطعي الفاكهة وضيفيها.": "Chop the fruit and add it.",
  "رشي القرفة.": "Sprinkle the cinnamon.",
  // s_banana_pb
  "موز بزبدة الفول السوداني": "Banana with peanut butter",
  "موزة صغيرة + معلقة كبيرة": "1 small banana + 1 tbsp",
  "١ موزة صغيرة": "1 small banana",
  "١ معلقة كبيرة زبدة فول سوداني من غير سكر": "1 tbsp unsweetened peanut butter",
  "قشري الموزة وقطعيها حلقات.": "Peel the banana and slice into rounds.",
  "افردي زبدة الفول السوداني على الحلقات.": "Spread the peanut butter on the rounds.",
  "ممكن تحطيها في الفريزر ١٠ دقايق.": "Optionally freeze for 10 minutes.",
  // s_banana_icecream
  "آيس كريم موز مجمد بالكاكاو": "Frozen banana \"ice cream\" with cocoa",
  "١ موزة ونص متقطعين ومتجمدين": "1.5 bananas, sliced and frozen",
  "١ معلقة صغيرة كاكاو خام": "1 tsp raw cocoa",
  "رشة فانيليا": "A pinch of vanilla",
  "قطعي الموز حلقات وجمديه ٤ ساعات على الأقل.": "Slice the bananas and freeze at least 4 hours.",
  "اضربيه في الكبة أو الخلاط مع الكاكاو والفانيليا.": "Blend in a food processor or blender with the cocoa and vanilla.",
  "اكشطي الجوانب لحد ما يبقى قوام آيس كريم ناعم.": "Scrape down the sides until it has a smooth ice-cream texture.",
  "كليه على طول أو جمديه نص ساعة.": "Eat right away or freeze 30 minutes.",
  // s_veggie_hummus
  "أصابع خضار مع حمص": "Vegetable sticks with hummus",
  "٣ معالق حمص + خضار": "3 tbsp hummus + vegetables",
  "٥٠ جم حمص بالطحينة": "50 g hummus with tahini",
  "حطي الحمص في بولة صغيرة.": "Put the hummus in a small bowl.",
  "غمسي الخضار في الحمص.": "Dip the vegetables in the hummus.",
  // s_nuts_mix
  "حفنة مكسرات ني": "A handful of raw nuts",
  "٢٥ جم": "25 g",
  "١٠ جم لوز ني": "10 g raw almonds",
  "١٠ جم عين جمل": "10 g walnuts",
  "٥ جم بندق ني": "5 g raw hazelnuts",
  "اوزني الكمية في بولة صغيرة عشان متزوديش.": "Weigh the portion into a small bowl so you don't overdo it.",
  "كليها على مهلك مع كوباية مية.": "Eat slowly with a glass of water.",
  "ممكن تحمصيها في الفرن ٥ دقايق من غير ملح.": "Optionally toast in the oven 5 minutes without salt.",
  // s_grilled_corn
  "درة مشوية": "Grilled corn on the cob",
  "كوز متوسط": "1 medium cob",
  "١ كوز درة متوسط": "1 medium corn cob",
  "رشة ملح خفيف وليمون": "A pinch of salt and lemon",
  "قشري الكوز من الورق.": "Husk the corn.",
  "اشويه على نار البوتاجاز أو في الفرن ١٥ دقيقة مع التقليب.": "Grill over the stove flame or in the oven 15 minutes, turning.",
  "رشي الليمون ورشة ملح خفيفة.": "Sprinkle with lemon and a light pinch of salt.",
};
